// Code generated by 'yaegi extract github.com/ethpandaops/spamoor/scenario'. DO NOT EDIT.

package symbols

import (
	"context"
	"github.com/ethpandaops/spamoor/scenario"
	"github.com/spf13/pflag"
	"reflect"
)

func init() {
	Symbols["github.com/ethpandaops/spamoor/scenario/scenario"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrNoClients":           reflect.ValueOf(&scenario.ErrNoClients).Elem(),
		"ErrNoWallet":            reflect.ValueOf(&scenario.ErrNoWallet).Elem(),
		"GetScenarioValidFields": reflect.ValueOf(scenario.GetScenarioValidFields),
		"GlobalSlotDuration":     reflect.ValueOf(&scenario.GlobalSlotDuration).Elem(),
		"NewConfigValidator":     reflect.ValueOf(scenario.NewConfigValidator),
		"NewRegistry":            reflect.ValueOf(scenario.NewRegistry),
		"ParseAndValidateConfig": reflect.ValueOf(scenario.ParseAndValidateConfig),
		"RunTransactionScenario": reflect.ValueOf(scenario.RunTransactionScenario),
		"ScenarioSourceNative":   reflect.ValueOf(scenario.ScenarioSourceNative),
		"ScenarioSourcePlugin":   reflect.ValueOf(scenario.ScenarioSourcePlugin),
		"ValidateScenarioConfig": reflect.ValueOf(scenario.ValidateScenarioConfig),

		// type definitions
		"Category":                   reflect.ValueOf((*scenario.Category)(nil)),
		"ConfigValidator":            reflect.ValueOf((*scenario.ConfigValidator)(nil)),
		"Descriptor":                 reflect.ValueOf((*scenario.Descriptor)(nil)),
		"FieldInfo":                  reflect.ValueOf((*scenario.FieldInfo)(nil)),
		"Options":                    reflect.ValueOf((*scenario.Options)(nil)),
		"PluginDescriptor":           reflect.ValueOf((*scenario.PluginDescriptor)(nil)),
		"ProcessNextTxParams":        reflect.ValueOf((*scenario.ProcessNextTxParams)(nil)),
		"ReceiptChan":                reflect.ValueOf((*scenario.ReceiptChan)(nil)),
		"Registry":                   reflect.ValueOf((*scenario.Registry)(nil)),
		"Scenario":                   reflect.ValueOf((*scenario.Scenario)(nil)),
		"ScenarioEntry":              reflect.ValueOf((*scenario.ScenarioEntry)(nil)),
		"ScenarioPlugin":             reflect.ValueOf((*scenario.ScenarioPlugin)(nil)),
		"ScenarioSource":             reflect.ValueOf((*scenario.ScenarioSource)(nil)),
		"TransactionScenarioOptions": reflect.ValueOf((*scenario.TransactionScenarioOptions)(nil)),
		"ValidationResult":           reflect.ValueOf((*scenario.ValidationResult)(nil)),

		// interface wrapper definitions
		"_Scenario":       reflect.ValueOf((*_github_com_ethpandaops_spamoor_scenario_Scenario)(nil)),
		"_ScenarioPlugin": reflect.ValueOf((*_github_com_ethpandaops_spamoor_scenario_ScenarioPlugin)(nil)),
	}
}

// _github_com_ethpandaops_spamoor_scenario_Scenario is an interface wrapper for Scenario type
type _github_com_ethpandaops_spamoor_scenario_Scenario struct {
	IValue interface{}
	WFlags func(flags *pflag.FlagSet) error
	WInit  func(options *scenario.Options) error
	WRun   func(ctx context.Context) error
}

func (W _github_com_ethpandaops_spamoor_scenario_Scenario) Flags(flags *pflag.FlagSet) error {
	return W.WFlags(flags)
}
func (W _github_com_ethpandaops_spamoor_scenario_Scenario) Init(options *scenario.Options) error {
	return W.WInit(options)
}
func (W _github_com_ethpandaops_spamoor_scenario_Scenario) Run(ctx context.Context) error {
	return W.WRun(ctx)
}

// _github_com_ethpandaops_spamoor_scenario_ScenarioPlugin is an interface wrapper for ScenarioPlugin type
type _github_com_ethpandaops_spamoor_scenario_ScenarioPlugin struct {
	IValue          interface{}
	WAddRunning     func()
	WGetDescription func() string
	WGetName        func() string
	WRemoveRunning  func()
}

func (W _github_com_ethpandaops_spamoor_scenario_ScenarioPlugin) AddRunning() { W.WAddRunning() }
func (W _github_com_ethpandaops_spamoor_scenario_ScenarioPlugin) GetDescription() string {
	return W.WGetDescription()
}
func (W _github_com_ethpandaops_spamoor_scenario_ScenarioPlugin) GetName() string {
	return W.WGetName()
}
func (W _github_com_ethpandaops_spamoor_scenario_ScenarioPlugin) RemoveRunning() { W.WRemoveRunning() }
