// Code generated by 'yaegi extract github.com/ethereum/go-ethereum/event'. DO NOT EDIT.

package symbols

import (
	"github.com/ethereum/go-ethereum/event"
	"reflect"
)

func init() {
	Symbols["github.com/ethereum/go-ethereum/event/event"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrMuxClosed":      reflect.ValueOf(&event.ErrMuxClosed).Elem(),
		"JoinSubscriptions": reflect.ValueOf(event.JoinSubscriptions),
		"NewSubscription":   reflect.ValueOf(event.NewSubscription),
		"Resubscribe":       reflect.ValueOf(event.Resubscribe),
		"ResubscribeErr":    reflect.ValueOf(event.ResubscribeErr),

		// type definitions
		"Feed":                reflect.ValueOf((*event.Feed)(nil)),
		"ResubscribeErrFunc":  reflect.ValueOf((*event.ResubscribeErrFunc)(nil)),
		"ResubscribeFunc":     reflect.ValueOf((*event.ResubscribeFunc)(nil)),
		"Subscription":        reflect.ValueOf((*event.Subscription)(nil)),
		"SubscriptionScope":   reflect.ValueOf((*event.SubscriptionScope)(nil)),
		"TypeMux":             reflect.ValueOf((*event.TypeMux)(nil)),
		"TypeMuxEvent":        reflect.ValueOf((*event.TypeMuxEvent)(nil)),
		"TypeMuxSubscription": reflect.ValueOf((*event.TypeMuxSubscription)(nil)),

		// interface wrapper definitions
		"_Subscription": reflect.ValueOf((*_github_com_ethereum_go_ethereum_event_Subscription)(nil)),
	}
}

// _github_com_ethereum_go_ethereum_event_Subscription is an interface wrapper for Subscription type
type _github_com_ethereum_go_ethereum_event_Subscription struct {
	IValue       interface{}
	WErr         func() <-chan error
	WUnsubscribe func()
}

func (W _github_com_ethereum_go_ethereum_event_Subscription) Err() <-chan error { return W.WErr() }
func (W _github_com_ethereum_go_ethereum_event_Subscription) Unsubscribe()      { W.WUnsubscribe() }
