// Code generated by 'yaegi extract github.com/ethereum/go-ethereum/accounts/abi/bind/v2'. DO NOT EDIT.

package symbols

import (
	"context"
	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi/bind/v2"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"math/big"
	"reflect"
)

func init() {
	Symbols["github.com/ethereum/go-ethereum/accounts/abi/bind/v2/bind"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DefaultDeployer":             reflect.ValueOf(bind.DefaultDeployer),
		"DeployContract":              reflect.ValueOf(bind.DeployContract),
		"DeployerWithNonceAssignment": reflect.ValueOf(bind.DeployerWithNonceAssignment),
		"ErrNoAddressInReceipt":       reflect.ValueOf(&bind.ErrNoAddressInReceipt).Elem(),
		"ErrNoBlockHashState":         reflect.ValueOf(&bind.ErrNoBlockHashState).Elem(),
		"ErrNoCode":                   reflect.ValueOf(&bind.ErrNoCode).Elem(),
		"ErrNoCodeAfterDeploy":        reflect.ValueOf(&bind.ErrNoCodeAfterDeploy).Elem(),
		"ErrNoPendingState":           reflect.ValueOf(&bind.ErrNoPendingState).Elem(),
		"ErrNotAuthorized":            reflect.ValueOf(&bind.ErrNotAuthorized).Elem(),
		"LinkAndDeploy":               reflect.ValueOf(bind.LinkAndDeploy),
		"NewBoundContract":            reflect.ValueOf(bind.NewBoundContract),
		"NewClefTransactor":           reflect.ValueOf(bind.NewClefTransactor),
		"NewKeyStoreTransactor":       reflect.ValueOf(bind.NewKeyStoreTransactor),
		"NewKeyedTransactor":          reflect.ValueOf(bind.NewKeyedTransactor),
		"Transact":                    reflect.ValueOf(bind.Transact),
		"WaitDeployed":                reflect.ValueOf(bind.WaitDeployed),
		"WaitMined":                   reflect.ValueOf(bind.WaitMined),

		// type definitions
		"Backend":                 reflect.ValueOf((*bind.Backend)(nil)),
		"BlockHashContractCaller": reflect.ValueOf((*bind.BlockHashContractCaller)(nil)),
		"BoundContract":           reflect.ValueOf((*bind.BoundContract)(nil)),
		"CallOpts":                reflect.ValueOf((*bind.CallOpts)(nil)),
		"ContractBackend":         reflect.ValueOf((*bind.ContractBackend)(nil)),
		"ContractCaller":          reflect.ValueOf((*bind.ContractCaller)(nil)),
		"ContractEvent":           reflect.ValueOf((*bind.ContractEvent)(nil)),
		"ContractFilterer":        reflect.ValueOf((*bind.ContractFilterer)(nil)),
		"ContractTransactor":      reflect.ValueOf((*bind.ContractTransactor)(nil)),
		"DeployBackend":           reflect.ValueOf((*bind.DeployBackend)(nil)),
		"DeployFn":                reflect.ValueOf((*bind.DeployFn)(nil)),
		"DeploymentParams":        reflect.ValueOf((*bind.DeploymentParams)(nil)),
		"DeploymentResult":        reflect.ValueOf((*bind.DeploymentResult)(nil)),
		"FilterOpts":              reflect.ValueOf((*bind.FilterOpts)(nil)),
		"MetaData":                reflect.ValueOf((*bind.MetaData)(nil)),
		"PendingContractCaller":   reflect.ValueOf((*bind.PendingContractCaller)(nil)),
		"SignerFn":                reflect.ValueOf((*bind.SignerFn)(nil)),
		"TransactOpts":            reflect.ValueOf((*bind.TransactOpts)(nil)),
		"WatchOpts":               reflect.ValueOf((*bind.WatchOpts)(nil)),

		// interface wrapper definitions
		"_Backend":                 reflect.ValueOf((*_github_com_ethereum_go_ethereum_accounts_abi_bind_v2_Backend)(nil)),
		"_BlockHashContractCaller": reflect.ValueOf((*_github_com_ethereum_go_ethereum_accounts_abi_bind_v2_BlockHashContractCaller)(nil)),
		"_ContractBackend":         reflect.ValueOf((*_github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractBackend)(nil)),
		"_ContractCaller":          reflect.ValueOf((*_github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractCaller)(nil)),
		"_ContractEvent":           reflect.ValueOf((*_github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractEvent)(nil)),
		"_ContractFilterer":        reflect.ValueOf((*_github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractFilterer)(nil)),
		"_ContractTransactor":      reflect.ValueOf((*_github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractTransactor)(nil)),
		"_DeployBackend":           reflect.ValueOf((*_github_com_ethereum_go_ethereum_accounts_abi_bind_v2_DeployBackend)(nil)),
		"_PendingContractCaller":   reflect.ValueOf((*_github_com_ethereum_go_ethereum_accounts_abi_bind_v2_PendingContractCaller)(nil)),
	}
}

// _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_Backend is an interface wrapper for Backend type
type _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_Backend struct {
	IValue               interface{}
	WCallContract        func(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error)
	WCodeAt              func(ctx context.Context, account common.Address, blockNumber *big.Int) ([]byte, error)
	WEstimateGas         func(ctx context.Context, call ethereum.CallMsg) (uint64, error)
	WFilterLogs          func(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error)
	WHeaderByNumber      func(ctx context.Context, number *big.Int) (*types.Header, error)
	WPendingCodeAt       func(ctx context.Context, account common.Address) ([]byte, error)
	WPendingNonceAt      func(ctx context.Context, account common.Address) (uint64, error)
	WSendTransaction     func(ctx context.Context, tx *types.Transaction) error
	WSubscribeFilterLogs func(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error)
	WSuggestGasPrice     func(ctx context.Context) (*big.Int, error)
	WSuggestGasTipCap    func(ctx context.Context) (*big.Int, error)
	WTransactionReceipt  func(ctx context.Context, txHash common.Hash) (*types.Receipt, error)
}

func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_Backend) CallContract(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error) {
	return W.WCallContract(ctx, call, blockNumber)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_Backend) CodeAt(ctx context.Context, account common.Address, blockNumber *big.Int) ([]byte, error) {
	return W.WCodeAt(ctx, account, blockNumber)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_Backend) EstimateGas(ctx context.Context, call ethereum.CallMsg) (uint64, error) {
	return W.WEstimateGas(ctx, call)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_Backend) FilterLogs(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error) {
	return W.WFilterLogs(ctx, q)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_Backend) HeaderByNumber(ctx context.Context, number *big.Int) (*types.Header, error) {
	return W.WHeaderByNumber(ctx, number)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_Backend) PendingCodeAt(ctx context.Context, account common.Address) ([]byte, error) {
	return W.WPendingCodeAt(ctx, account)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_Backend) PendingNonceAt(ctx context.Context, account common.Address) (uint64, error) {
	return W.WPendingNonceAt(ctx, account)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_Backend) SendTransaction(ctx context.Context, tx *types.Transaction) error {
	return W.WSendTransaction(ctx, tx)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_Backend) SubscribeFilterLogs(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error) {
	return W.WSubscribeFilterLogs(ctx, q, ch)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_Backend) SuggestGasPrice(ctx context.Context) (*big.Int, error) {
	return W.WSuggestGasPrice(ctx)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_Backend) SuggestGasTipCap(ctx context.Context) (*big.Int, error) {
	return W.WSuggestGasTipCap(ctx)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_Backend) TransactionReceipt(ctx context.Context, txHash common.Hash) (*types.Receipt, error) {
	return W.WTransactionReceipt(ctx, txHash)
}

// _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_BlockHashContractCaller is an interface wrapper for BlockHashContractCaller type
type _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_BlockHashContractCaller struct {
	IValue              interface{}
	WCallContractAtHash func(ctx context.Context, call ethereum.CallMsg, blockHash common.Hash) ([]byte, error)
	WCodeAtHash         func(ctx context.Context, contract common.Address, blockHash common.Hash) ([]byte, error)
}

func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_BlockHashContractCaller) CallContractAtHash(ctx context.Context, call ethereum.CallMsg, blockHash common.Hash) ([]byte, error) {
	return W.WCallContractAtHash(ctx, call, blockHash)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_BlockHashContractCaller) CodeAtHash(ctx context.Context, contract common.Address, blockHash common.Hash) ([]byte, error) {
	return W.WCodeAtHash(ctx, contract, blockHash)
}

// _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractBackend is an interface wrapper for ContractBackend type
type _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractBackend struct {
	IValue               interface{}
	WCallContract        func(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error)
	WCodeAt              func(ctx context.Context, contract common.Address, blockNumber *big.Int) ([]byte, error)
	WEstimateGas         func(ctx context.Context, call ethereum.CallMsg) (uint64, error)
	WFilterLogs          func(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error)
	WHeaderByNumber      func(ctx context.Context, number *big.Int) (*types.Header, error)
	WPendingCodeAt       func(ctx context.Context, account common.Address) ([]byte, error)
	WPendingNonceAt      func(ctx context.Context, account common.Address) (uint64, error)
	WSendTransaction     func(ctx context.Context, tx *types.Transaction) error
	WSubscribeFilterLogs func(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error)
	WSuggestGasPrice     func(ctx context.Context) (*big.Int, error)
	WSuggestGasTipCap    func(ctx context.Context) (*big.Int, error)
}

func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractBackend) CallContract(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error) {
	return W.WCallContract(ctx, call, blockNumber)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractBackend) CodeAt(ctx context.Context, contract common.Address, blockNumber *big.Int) ([]byte, error) {
	return W.WCodeAt(ctx, contract, blockNumber)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractBackend) EstimateGas(ctx context.Context, call ethereum.CallMsg) (uint64, error) {
	return W.WEstimateGas(ctx, call)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractBackend) FilterLogs(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error) {
	return W.WFilterLogs(ctx, q)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractBackend) HeaderByNumber(ctx context.Context, number *big.Int) (*types.Header, error) {
	return W.WHeaderByNumber(ctx, number)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractBackend) PendingCodeAt(ctx context.Context, account common.Address) ([]byte, error) {
	return W.WPendingCodeAt(ctx, account)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractBackend) PendingNonceAt(ctx context.Context, account common.Address) (uint64, error) {
	return W.WPendingNonceAt(ctx, account)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractBackend) SendTransaction(ctx context.Context, tx *types.Transaction) error {
	return W.WSendTransaction(ctx, tx)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractBackend) SubscribeFilterLogs(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error) {
	return W.WSubscribeFilterLogs(ctx, q, ch)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractBackend) SuggestGasPrice(ctx context.Context) (*big.Int, error) {
	return W.WSuggestGasPrice(ctx)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractBackend) SuggestGasTipCap(ctx context.Context) (*big.Int, error) {
	return W.WSuggestGasTipCap(ctx)
}

// _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractCaller is an interface wrapper for ContractCaller type
type _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractCaller struct {
	IValue        interface{}
	WCallContract func(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error)
	WCodeAt       func(ctx context.Context, contract common.Address, blockNumber *big.Int) ([]byte, error)
}

func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractCaller) CallContract(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error) {
	return W.WCallContract(ctx, call, blockNumber)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractCaller) CodeAt(ctx context.Context, contract common.Address, blockNumber *big.Int) ([]byte, error) {
	return W.WCodeAt(ctx, contract, blockNumber)
}

// _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractEvent is an interface wrapper for ContractEvent type
type _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractEvent struct {
	IValue             interface{}
	WContractEventName func() string
}

func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractEvent) ContractEventName() string {
	return W.WContractEventName()
}

// _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractFilterer is an interface wrapper for ContractFilterer type
type _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractFilterer struct {
	IValue               interface{}
	WFilterLogs          func(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error)
	WSubscribeFilterLogs func(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error)
}

func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractFilterer) FilterLogs(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error) {
	return W.WFilterLogs(ctx, q)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractFilterer) SubscribeFilterLogs(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error) {
	return W.WSubscribeFilterLogs(ctx, q, ch)
}

// _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractTransactor is an interface wrapper for ContractTransactor type
type _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractTransactor struct {
	IValue            interface{}
	WEstimateGas      func(ctx context.Context, call ethereum.CallMsg) (uint64, error)
	WHeaderByNumber   func(ctx context.Context, number *big.Int) (*types.Header, error)
	WPendingCodeAt    func(ctx context.Context, account common.Address) ([]byte, error)
	WPendingNonceAt   func(ctx context.Context, account common.Address) (uint64, error)
	WSendTransaction  func(ctx context.Context, tx *types.Transaction) error
	WSuggestGasPrice  func(ctx context.Context) (*big.Int, error)
	WSuggestGasTipCap func(ctx context.Context) (*big.Int, error)
}

func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractTransactor) EstimateGas(ctx context.Context, call ethereum.CallMsg) (uint64, error) {
	return W.WEstimateGas(ctx, call)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractTransactor) HeaderByNumber(ctx context.Context, number *big.Int) (*types.Header, error) {
	return W.WHeaderByNumber(ctx, number)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractTransactor) PendingCodeAt(ctx context.Context, account common.Address) ([]byte, error) {
	return W.WPendingCodeAt(ctx, account)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractTransactor) PendingNonceAt(ctx context.Context, account common.Address) (uint64, error) {
	return W.WPendingNonceAt(ctx, account)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractTransactor) SendTransaction(ctx context.Context, tx *types.Transaction) error {
	return W.WSendTransaction(ctx, tx)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractTransactor) SuggestGasPrice(ctx context.Context) (*big.Int, error) {
	return W.WSuggestGasPrice(ctx)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_ContractTransactor) SuggestGasTipCap(ctx context.Context) (*big.Int, error) {
	return W.WSuggestGasTipCap(ctx)
}

// _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_DeployBackend is an interface wrapper for DeployBackend type
type _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_DeployBackend struct {
	IValue              interface{}
	WCodeAt             func(ctx context.Context, account common.Address, blockNumber *big.Int) ([]byte, error)
	WTransactionReceipt func(ctx context.Context, txHash common.Hash) (*types.Receipt, error)
}

func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_DeployBackend) CodeAt(ctx context.Context, account common.Address, blockNumber *big.Int) ([]byte, error) {
	return W.WCodeAt(ctx, account, blockNumber)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_DeployBackend) TransactionReceipt(ctx context.Context, txHash common.Hash) (*types.Receipt, error) {
	return W.WTransactionReceipt(ctx, txHash)
}

// _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_PendingContractCaller is an interface wrapper for PendingContractCaller type
type _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_PendingContractCaller struct {
	IValue               interface{}
	WPendingCallContract func(ctx context.Context, call ethereum.CallMsg) ([]byte, error)
	WPendingCodeAt       func(ctx context.Context, contract common.Address) ([]byte, error)
}

func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_PendingContractCaller) PendingCallContract(ctx context.Context, call ethereum.CallMsg) ([]byte, error) {
	return W.WPendingCallContract(ctx, call)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_v2_PendingContractCaller) PendingCodeAt(ctx context.Context, contract common.Address) ([]byte, error) {
	return W.WPendingCodeAt(ctx, contract)
}
