// Code generated by 'yaegi extract github.com/ethpandaops/spamoor/spamoor'. DO NOT EDIT.

package symbols

import (
	"github.com/ethpandaops/spamoor/spamoor"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/ethpandaops/spamoor/spamoor/spamoor"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"BatcherBaseGas":               reflect.ValueOf(constant.MakeFromLiteral("50000", token.INT, 0)),
		"BatcherGasPerTx":              reflect.ValueOf(constant.MakeFromLiteral("35000", token.INT, 0)),
		"BatcherTxLimit":               reflect.ValueOf(constant.MakeFromLiteral("450", token.INT, 0)),
		"ClientTypeBuilder":            reflect.ValueOf(spamoor.ClientTypeBuilder),
		"ClientTypeClient":             reflect.ValueOf(spamoor.ClientTypeClient),
		"GetDefaultLogFn":              reflect.ValueOf(spamoor.GetDefaultLogFn),
		"GetDefaultWalletConfig":       reflect.ValueOf(spamoor.GetDefaultWalletConfig),
		"InitRootWallet":               reflect.ValueOf(spamoor.InitRootWallet),
		"LoadPrivateKey":               reflect.ValueOf(spamoor.LoadPrivateKey),
		"NewClient":                    reflect.ValueOf(spamoor.NewClient),
		"NewClientPool":                reflect.ValueOf(spamoor.NewClientPool),
		"NewTxBatcher":                 reflect.ValueOf(spamoor.NewTxBatcher),
		"NewTxPool":                    reflect.ValueOf(spamoor.NewTxPool),
		"NewWallet":                    reflect.ValueOf(spamoor.NewWallet),
		"NewWalletPool":                reflect.ValueOf(spamoor.NewWalletPool),
		"ResolveFees":                  reflect.ValueOf(spamoor.ResolveFees),
		"SelectClientByIndex":          reflect.ValueOf(&spamoor.SelectClientByIndex).Elem(),
		"SelectClientRandom":           reflect.ValueOf(&spamoor.SelectClientRandom).Elem(),
		"SelectClientRoundRobin":       reflect.ValueOf(&spamoor.SelectClientRoundRobin).Elem(),
		"SelectWalletByIndex":          reflect.ValueOf(&spamoor.SelectWalletByIndex).Elem(),
		"SelectWalletByPendingTxCount": reflect.ValueOf(&spamoor.SelectWalletByPendingTxCount).Elem(),
		"SelectWalletRandom":           reflect.ValueOf(&spamoor.SelectWalletRandom).Elem(),
		"SelectWalletRoundRobin":       reflect.ValueOf(&spamoor.SelectWalletRoundRobin).Elem(),
		"WithClientGroup":              reflect.ValueOf(spamoor.WithClientGroup),
		"WithClientSelectionMode":      reflect.ValueOf(spamoor.WithClientSelectionMode),
		"WithoutBuilder":               reflect.ValueOf(spamoor.WithoutBuilder),
		"WithoutClientType":            reflect.ValueOf(spamoor.WithoutClientType),

		// type definitions
		"BatchOptions":           reflect.ValueOf((*spamoor.BatchOptions)(nil)),
		"BlockInfo":              reflect.ValueOf((*spamoor.BlockInfo)(nil)),
		"BlockStatsCallback":     reflect.ValueOf((*spamoor.BlockStatsCallback)(nil)),
		"BlockSubscription":      reflect.ValueOf((*spamoor.BlockSubscription)(nil)),
		"BlockWithHash":          reflect.ValueOf((*spamoor.BlockWithHash)(nil)),
		"BulkBlockStatsCallback": reflect.ValueOf((*spamoor.BulkBlockStatsCallback)(nil)),
		"BulkBlockSubscription":  reflect.ValueOf((*spamoor.BulkBlockSubscription)(nil)),
		"Client":                 reflect.ValueOf((*spamoor.Client)(nil)),
		"ClientOptions":          reflect.ValueOf((*spamoor.ClientOptions)(nil)),
		"ClientPool":             reflect.ValueOf((*spamoor.ClientPool)(nil)),
		"ClientSelectionMode":    reflect.ValueOf((*spamoor.ClientSelectionMode)(nil)),
		"ClientSelectionOption":  reflect.ValueOf((*spamoor.ClientSelectionOption)(nil)),
		"ClientType":             reflect.ValueOf((*spamoor.ClientType)(nil)),
		"ExternalBlockEvent":     reflect.ValueOf((*spamoor.ExternalBlockEvent)(nil)),
		"ExternalBlockSource":    reflect.ValueOf((*spamoor.ExternalBlockSource)(nil)),
		"ExternalClientOptions":  reflect.ValueOf((*spamoor.ExternalClientOptions)(nil)),
		"FundingRequest":         reflect.ValueOf((*spamoor.FundingRequest)(nil)),
		"GlobalBlockStats":       reflect.ValueOf((*spamoor.GlobalBlockStats)(nil)),
		"PendingTx":              reflect.ValueOf((*spamoor.PendingTx)(nil)),
		"RootWallet":             reflect.ValueOf((*spamoor.RootWallet)(nil)),
		"SendTransactionOptions": reflect.ValueOf((*spamoor.SendTransactionOptions)(nil)),
		"TxBatcher":              reflect.ValueOf((*spamoor.TxBatcher)(nil)),
		"TxCompleteFn":           reflect.ValueOf((*spamoor.TxCompleteFn)(nil)),
		"TxConfirmFn":            reflect.ValueOf((*spamoor.TxConfirmFn)(nil)),
		"TxEncodeFn":             reflect.ValueOf((*spamoor.TxEncodeFn)(nil)),
		"TxInfo":                 reflect.ValueOf((*spamoor.TxInfo)(nil)),
		"TxLogFn":                reflect.ValueOf((*spamoor.TxLogFn)(nil)),
		"TxPool":                 reflect.ValueOf((*spamoor.TxPool)(nil)),
		"TxPoolOptions":          reflect.ValueOf((*spamoor.TxPoolOptions)(nil)),
		"Wallet":                 reflect.ValueOf((*spamoor.Wallet)(nil)),
		"WalletPool":             reflect.ValueOf((*spamoor.WalletPool)(nil)),
		"WalletPoolBlockStats":   reflect.ValueOf((*spamoor.WalletPoolBlockStats)(nil)),
		"WalletPoolConfig":       reflect.ValueOf((*spamoor.WalletPoolConfig)(nil)),
		"WalletSelectionMode":    reflect.ValueOf((*spamoor.WalletSelectionMode)(nil)),
		"WellKnownWalletConfig":  reflect.ValueOf((*spamoor.WellKnownWalletConfig)(nil)),

		// interface wrapper definitions
		"_ClientSelectionOption": reflect.ValueOf((*_github_com_ethpandaops_spamoor_spamoor_ClientSelectionOption)(nil)),
	}
}

// _github_com_ethpandaops_spamoor_spamoor_ClientSelectionOption is an interface wrapper for ClientSelectionOption type
type _github_com_ethpandaops_spamoor_spamoor_ClientSelectionOption struct {
	IValue interface{}
}
