// Code generated by 'yaegi extract github.com/ethereum/go-ethereum'. DO NOT EDIT.

package symbols

import (
	"context"
	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"math/big"
	"reflect"
)

func init() {
	Symbols["github.com/ethereum/go-ethereum/ethereum"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"NotFound": reflect.ValueOf(&ethereum.NotFound).Elem(),

		// type definitions
		"BlockNumberReader":        reflect.ValueOf((*ethereum.BlockNumberReader)(nil)),
		"BlockOverrides":           reflect.ValueOf((*ethereum.BlockOverrides)(nil)),
		"CallMsg":                  reflect.ValueOf((*ethereum.CallMsg)(nil)),
		"ChainIDReader":            reflect.ValueOf((*ethereum.ChainIDReader)(nil)),
		"ChainReader":              reflect.ValueOf((*ethereum.ChainReader)(nil)),
		"ChainStateReader":         reflect.ValueOf((*ethereum.ChainStateReader)(nil)),
		"ChainSyncReader":          reflect.ValueOf((*ethereum.ChainSyncReader)(nil)),
		"ContractCaller":           reflect.ValueOf((*ethereum.ContractCaller)(nil)),
		"FeeHistory":               reflect.ValueOf((*ethereum.FeeHistory)(nil)),
		"FeeHistoryReader":         reflect.ValueOf((*ethereum.FeeHistoryReader)(nil)),
		"FilterQuery":              reflect.ValueOf((*ethereum.FilterQuery)(nil)),
		"GasEstimator":             reflect.ValueOf((*ethereum.GasEstimator)(nil)),
		"GasPricer":                reflect.ValueOf((*ethereum.GasPricer)(nil)),
		"GasPricer1559":            reflect.ValueOf((*ethereum.GasPricer1559)(nil)),
		"LogFilterer":              reflect.ValueOf((*ethereum.LogFilterer)(nil)),
		"OverrideAccount":          reflect.ValueOf((*ethereum.OverrideAccount)(nil)),
		"PendingContractCaller":    reflect.ValueOf((*ethereum.PendingContractCaller)(nil)),
		"PendingStateEventer":      reflect.ValueOf((*ethereum.PendingStateEventer)(nil)),
		"PendingStateReader":       reflect.ValueOf((*ethereum.PendingStateReader)(nil)),
		"Subscription":             reflect.ValueOf((*ethereum.Subscription)(nil)),
		"SyncProgress":             reflect.ValueOf((*ethereum.SyncProgress)(nil)),
		"TransactionReader":        reflect.ValueOf((*ethereum.TransactionReader)(nil)),
		"TransactionReceiptsQuery": reflect.ValueOf((*ethereum.TransactionReceiptsQuery)(nil)),
		"TransactionSender":        reflect.ValueOf((*ethereum.TransactionSender)(nil)),

		// interface wrapper definitions
		"_BlockNumberReader":     reflect.ValueOf((*_github_com_ethereum_go_ethereum_BlockNumberReader)(nil)),
		"_ChainIDReader":         reflect.ValueOf((*_github_com_ethereum_go_ethereum_ChainIDReader)(nil)),
		"_ChainReader":           reflect.ValueOf((*_github_com_ethereum_go_ethereum_ChainReader)(nil)),
		"_ChainStateReader":      reflect.ValueOf((*_github_com_ethereum_go_ethereum_ChainStateReader)(nil)),
		"_ChainSyncReader":       reflect.ValueOf((*_github_com_ethereum_go_ethereum_ChainSyncReader)(nil)),
		"_ContractCaller":        reflect.ValueOf((*_github_com_ethereum_go_ethereum_ContractCaller)(nil)),
		"_FeeHistoryReader":      reflect.ValueOf((*_github_com_ethereum_go_ethereum_FeeHistoryReader)(nil)),
		"_GasEstimator":          reflect.ValueOf((*_github_com_ethereum_go_ethereum_GasEstimator)(nil)),
		"_GasPricer":             reflect.ValueOf((*_github_com_ethereum_go_ethereum_GasPricer)(nil)),
		"_GasPricer1559":         reflect.ValueOf((*_github_com_ethereum_go_ethereum_GasPricer1559)(nil)),
		"_LogFilterer":           reflect.ValueOf((*_github_com_ethereum_go_ethereum_LogFilterer)(nil)),
		"_PendingContractCaller": reflect.ValueOf((*_github_com_ethereum_go_ethereum_PendingContractCaller)(nil)),
		"_PendingStateEventer":   reflect.ValueOf((*_github_com_ethereum_go_ethereum_PendingStateEventer)(nil)),
		"_PendingStateReader":    reflect.ValueOf((*_github_com_ethereum_go_ethereum_PendingStateReader)(nil)),
		"_Subscription":          reflect.ValueOf((*_github_com_ethereum_go_ethereum_Subscription)(nil)),
		"_TransactionReader":     reflect.ValueOf((*_github_com_ethereum_go_ethereum_TransactionReader)(nil)),
		"_TransactionSender":     reflect.ValueOf((*_github_com_ethereum_go_ethereum_TransactionSender)(nil)),
	}
}

// _github_com_ethereum_go_ethereum_BlockNumberReader is an interface wrapper for BlockNumberReader type
type _github_com_ethereum_go_ethereum_BlockNumberReader struct {
	IValue       interface{}
	WBlockNumber func(ctx context.Context) (uint64, error)
}

func (W _github_com_ethereum_go_ethereum_BlockNumberReader) BlockNumber(ctx context.Context) (uint64, error) {
	return W.WBlockNumber(ctx)
}

// _github_com_ethereum_go_ethereum_ChainIDReader is an interface wrapper for ChainIDReader type
type _github_com_ethereum_go_ethereum_ChainIDReader struct {
	IValue   interface{}
	WChainID func(ctx context.Context) (*big.Int, error)
}

func (W _github_com_ethereum_go_ethereum_ChainIDReader) ChainID(ctx context.Context) (*big.Int, error) {
	return W.WChainID(ctx)
}

// _github_com_ethereum_go_ethereum_ChainReader is an interface wrapper for ChainReader type
type _github_com_ethereum_go_ethereum_ChainReader struct {
	IValue              interface{}
	WBlockByHash        func(ctx context.Context, hash common.Hash) (*types.Block, error)
	WBlockByNumber      func(ctx context.Context, number *big.Int) (*types.Block, error)
	WHeaderByHash       func(ctx context.Context, hash common.Hash) (*types.Header, error)
	WHeaderByNumber     func(ctx context.Context, number *big.Int) (*types.Header, error)
	WSubscribeNewHead   func(ctx context.Context, ch chan<- *types.Header) (ethereum.Subscription, error)
	WTransactionCount   func(ctx context.Context, blockHash common.Hash) (uint, error)
	WTransactionInBlock func(ctx context.Context, blockHash common.Hash, index uint) (*types.Transaction, error)
}

func (W _github_com_ethereum_go_ethereum_ChainReader) BlockByHash(ctx context.Context, hash common.Hash) (*types.Block, error) {
	return W.WBlockByHash(ctx, hash)
}
func (W _github_com_ethereum_go_ethereum_ChainReader) BlockByNumber(ctx context.Context, number *big.Int) (*types.Block, error) {
	return W.WBlockByNumber(ctx, number)
}
func (W _github_com_ethereum_go_ethereum_ChainReader) HeaderByHash(ctx context.Context, hash common.Hash) (*types.Header, error) {
	return W.WHeaderByHash(ctx, hash)
}
func (W _github_com_ethereum_go_ethereum_ChainReader) HeaderByNumber(ctx context.Context, number *big.Int) (*types.Header, error) {
	return W.WHeaderByNumber(ctx, number)
}
func (W _github_com_ethereum_go_ethereum_ChainReader) SubscribeNewHead(ctx context.Context, ch chan<- *types.Header) (ethereum.Subscription, error) {
	return W.WSubscribeNewHead(ctx, ch)
}
func (W _github_com_ethereum_go_ethereum_ChainReader) TransactionCount(ctx context.Context, blockHash common.Hash) (uint, error) {
	return W.WTransactionCount(ctx, blockHash)
}
func (W _github_com_ethereum_go_ethereum_ChainReader) TransactionInBlock(ctx context.Context, blockHash common.Hash, index uint) (*types.Transaction, error) {
	return W.WTransactionInBlock(ctx, blockHash, index)
}

// _github_com_ethereum_go_ethereum_ChainStateReader is an interface wrapper for ChainStateReader type
type _github_com_ethereum_go_ethereum_ChainStateReader struct {
	IValue     interface{}
	WBalanceAt func(ctx context.Context, account common.Address, blockNumber *big.Int) (*big.Int, error)
	WCodeAt    func(ctx context.Context, account common.Address, blockNumber *big.Int) ([]byte, error)
	WNonceAt   func(ctx context.Context, account common.Address, blockNumber *big.Int) (uint64, error)
	WStorageAt func(ctx context.Context, account common.Address, key common.Hash, blockNumber *big.Int) ([]byte, error)
}

func (W _github_com_ethereum_go_ethereum_ChainStateReader) BalanceAt(ctx context.Context, account common.Address, blockNumber *big.Int) (*big.Int, error) {
	return W.WBalanceAt(ctx, account, blockNumber)
}
func (W _github_com_ethereum_go_ethereum_ChainStateReader) CodeAt(ctx context.Context, account common.Address, blockNumber *big.Int) ([]byte, error) {
	return W.WCodeAt(ctx, account, blockNumber)
}
func (W _github_com_ethereum_go_ethereum_ChainStateReader) NonceAt(ctx context.Context, account common.Address, blockNumber *big.Int) (uint64, error) {
	return W.WNonceAt(ctx, account, blockNumber)
}
func (W _github_com_ethereum_go_ethereum_ChainStateReader) StorageAt(ctx context.Context, account common.Address, key common.Hash, blockNumber *big.Int) ([]byte, error) {
	return W.WStorageAt(ctx, account, key, blockNumber)
}

// _github_com_ethereum_go_ethereum_ChainSyncReader is an interface wrapper for ChainSyncReader type
type _github_com_ethereum_go_ethereum_ChainSyncReader struct {
	IValue        interface{}
	WSyncProgress func(ctx context.Context) (*ethereum.SyncProgress, error)
}

func (W _github_com_ethereum_go_ethereum_ChainSyncReader) SyncProgress(ctx context.Context) (*ethereum.SyncProgress, error) {
	return W.WSyncProgress(ctx)
}

// _github_com_ethereum_go_ethereum_ContractCaller is an interface wrapper for ContractCaller type
type _github_com_ethereum_go_ethereum_ContractCaller struct {
	IValue        interface{}
	WCallContract func(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error)
}

func (W _github_com_ethereum_go_ethereum_ContractCaller) CallContract(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error) {
	return W.WCallContract(ctx, call, blockNumber)
}

// _github_com_ethereum_go_ethereum_FeeHistoryReader is an interface wrapper for FeeHistoryReader type
type _github_com_ethereum_go_ethereum_FeeHistoryReader struct {
	IValue      interface{}
	WFeeHistory func(ctx context.Context, blockCount uint64, lastBlock *big.Int, rewardPercentiles []float64) (*ethereum.FeeHistory, error)
}

func (W _github_com_ethereum_go_ethereum_FeeHistoryReader) FeeHistory(ctx context.Context, blockCount uint64, lastBlock *big.Int, rewardPercentiles []float64) (*ethereum.FeeHistory, error) {
	return W.WFeeHistory(ctx, blockCount, lastBlock, rewardPercentiles)
}

// _github_com_ethereum_go_ethereum_GasEstimator is an interface wrapper for GasEstimator type
type _github_com_ethereum_go_ethereum_GasEstimator struct {
	IValue       interface{}
	WEstimateGas func(ctx context.Context, call ethereum.CallMsg) (uint64, error)
}

func (W _github_com_ethereum_go_ethereum_GasEstimator) EstimateGas(ctx context.Context, call ethereum.CallMsg) (uint64, error) {
	return W.WEstimateGas(ctx, call)
}

// _github_com_ethereum_go_ethereum_GasPricer is an interface wrapper for GasPricer type
type _github_com_ethereum_go_ethereum_GasPricer struct {
	IValue           interface{}
	WSuggestGasPrice func(ctx context.Context) (*big.Int, error)
}

func (W _github_com_ethereum_go_ethereum_GasPricer) SuggestGasPrice(ctx context.Context) (*big.Int, error) {
	return W.WSuggestGasPrice(ctx)
}

// _github_com_ethereum_go_ethereum_GasPricer1559 is an interface wrapper for GasPricer1559 type
type _github_com_ethereum_go_ethereum_GasPricer1559 struct {
	IValue            interface{}
	WSuggestGasTipCap func(ctx context.Context) (*big.Int, error)
}

func (W _github_com_ethereum_go_ethereum_GasPricer1559) SuggestGasTipCap(ctx context.Context) (*big.Int, error) {
	return W.WSuggestGasTipCap(ctx)
}

// _github_com_ethereum_go_ethereum_LogFilterer is an interface wrapper for LogFilterer type
type _github_com_ethereum_go_ethereum_LogFilterer struct {
	IValue               interface{}
	WFilterLogs          func(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error)
	WSubscribeFilterLogs func(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error)
}

func (W _github_com_ethereum_go_ethereum_LogFilterer) FilterLogs(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error) {
	return W.WFilterLogs(ctx, q)
}
func (W _github_com_ethereum_go_ethereum_LogFilterer) SubscribeFilterLogs(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error) {
	return W.WSubscribeFilterLogs(ctx, q, ch)
}

// _github_com_ethereum_go_ethereum_PendingContractCaller is an interface wrapper for PendingContractCaller type
type _github_com_ethereum_go_ethereum_PendingContractCaller struct {
	IValue               interface{}
	WPendingCallContract func(ctx context.Context, call ethereum.CallMsg) ([]byte, error)
}

func (W _github_com_ethereum_go_ethereum_PendingContractCaller) PendingCallContract(ctx context.Context, call ethereum.CallMsg) ([]byte, error) {
	return W.WPendingCallContract(ctx, call)
}

// _github_com_ethereum_go_ethereum_PendingStateEventer is an interface wrapper for PendingStateEventer type
type _github_com_ethereum_go_ethereum_PendingStateEventer struct {
	IValue                        interface{}
	WSubscribePendingTransactions func(ctx context.Context, ch chan<- *types.Transaction) (ethereum.Subscription, error)
}

func (W _github_com_ethereum_go_ethereum_PendingStateEventer) SubscribePendingTransactions(ctx context.Context, ch chan<- *types.Transaction) (ethereum.Subscription, error) {
	return W.WSubscribePendingTransactions(ctx, ch)
}

// _github_com_ethereum_go_ethereum_PendingStateReader is an interface wrapper for PendingStateReader type
type _github_com_ethereum_go_ethereum_PendingStateReader struct {
	IValue                   interface{}
	WPendingBalanceAt        func(ctx context.Context, account common.Address) (*big.Int, error)
	WPendingCodeAt           func(ctx context.Context, account common.Address) ([]byte, error)
	WPendingNonceAt          func(ctx context.Context, account common.Address) (uint64, error)
	WPendingStorageAt        func(ctx context.Context, account common.Address, key common.Hash) ([]byte, error)
	WPendingTransactionCount func(ctx context.Context) (uint, error)
}

func (W _github_com_ethereum_go_ethereum_PendingStateReader) PendingBalanceAt(ctx context.Context, account common.Address) (*big.Int, error) {
	return W.WPendingBalanceAt(ctx, account)
}
func (W _github_com_ethereum_go_ethereum_PendingStateReader) PendingCodeAt(ctx context.Context, account common.Address) ([]byte, error) {
	return W.WPendingCodeAt(ctx, account)
}
func (W _github_com_ethereum_go_ethereum_PendingStateReader) PendingNonceAt(ctx context.Context, account common.Address) (uint64, error) {
	return W.WPendingNonceAt(ctx, account)
}
func (W _github_com_ethereum_go_ethereum_PendingStateReader) PendingStorageAt(ctx context.Context, account common.Address, key common.Hash) ([]byte, error) {
	return W.WPendingStorageAt(ctx, account, key)
}
func (W _github_com_ethereum_go_ethereum_PendingStateReader) PendingTransactionCount(ctx context.Context) (uint, error) {
	return W.WPendingTransactionCount(ctx)
}

// _github_com_ethereum_go_ethereum_Subscription is an interface wrapper for Subscription type
type _github_com_ethereum_go_ethereum_Subscription struct {
	IValue       interface{}
	WErr         func() <-chan error
	WUnsubscribe func()
}

func (W _github_com_ethereum_go_ethereum_Subscription) Err() <-chan error {
	return W.WErr()
}
func (W _github_com_ethereum_go_ethereum_Subscription) Unsubscribe() {
	W.WUnsubscribe()
}

// _github_com_ethereum_go_ethereum_TransactionReader is an interface wrapper for TransactionReader type
type _github_com_ethereum_go_ethereum_TransactionReader struct {
	IValue                        interface{}
	WSubscribeTransactionReceipts func(ctx context.Context, q *ethereum.TransactionReceiptsQuery, ch chan<- []*types.Receipt) (ethereum.Subscription, error)
	WTransactionByHash            func(ctx context.Context, txHash common.Hash) (tx *types.Transaction, isPending bool, err error)
	WTransactionReceipt           func(ctx context.Context, txHash common.Hash) (*types.Receipt, error)
}

func (W _github_com_ethereum_go_ethereum_TransactionReader) SubscribeTransactionReceipts(ctx context.Context, q *ethereum.TransactionReceiptsQuery, ch chan<- []*types.Receipt) (ethereum.Subscription, error) {
	return W.WSubscribeTransactionReceipts(ctx, q, ch)
}
func (W _github_com_ethereum_go_ethereum_TransactionReader) TransactionByHash(ctx context.Context, txHash common.Hash) (tx *types.Transaction, isPending bool, err error) {
	return W.WTransactionByHash(ctx, txHash)
}
func (W _github_com_ethereum_go_ethereum_TransactionReader) TransactionReceipt(ctx context.Context, txHash common.Hash) (*types.Receipt, error) {
	return W.WTransactionReceipt(ctx, txHash)
}

// _github_com_ethereum_go_ethereum_TransactionSender is an interface wrapper for TransactionSender type
type _github_com_ethereum_go_ethereum_TransactionSender struct {
	IValue           interface{}
	WSendTransaction func(ctx context.Context, tx *types.Transaction) error
}

func (W _github_com_ethereum_go_ethereum_TransactionSender) SendTransaction(ctx context.Context, tx *types.Transaction) error {
	return W.WSendTransaction(ctx, tx)
}
