// Code generated by 'yaegi extract github.com/ethpandaops/spamoor/txtypes'. DO NOT EDIT.

package symbols

import (
	"bytes"
	"crypto/ecdsa"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethpandaops/spamoor/txtypes"
	"go/constant"
	"go/token"
	"math/big"
	"reflect"
)

func init() {
	Symbols["github.com/ethpandaops/spamoor/txtypes/txtypes"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AccessListTxType":           reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"AddressToDelegation":        reflect.ValueOf(txtypes.AddressToDelegation),
		"ApproveExecution":           reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"ApproveExecutionAndPayment": reflect.ValueOf(constant.MakeFromLiteral("3", token.INT, 0)),
		"ApproveNone":                reflect.ValueOf(constant.MakeFromLiteral("0", token.INT, 0)),
		"ApprovePayment":             reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"ApproveScopeMask":           reflect.ValueOf(constant.MakeFromLiteral("3", token.INT, 0)),
		"ArbitrarySignature":         reflect.ValueOf(txtypes.ArbitrarySignature),
		"AtomicBatchFlag":            reflect.ValueOf(constant.MakeFromLiteral("4", token.INT, 0)),
		"BlobSidecarVersion0":        reflect.ValueOf(txtypes.BlobSidecarVersion0),
		"BlobSidecarVersion1":        reflect.ValueOf(txtypes.BlobSidecarVersion1),
		"BlobTxType":                 reflect.ValueOf(constant.MakeFromLiteral("3", token.INT, 0)),
		"CostPerStateByte":           reflect.ValueOf(constant.MakeFromLiteral("1530", token.INT, 0)),
		"DecodeTx":                   reflect.ValueOf(txtypes.DecodeTx),
		"DefaultCodeVerifyLimits":    reflect.ValueOf(txtypes.DefaultCodeVerifyLimits),
		"DelegationPrefix":           reflect.ValueOf(&txtypes.DelegationPrefix).Elem(),
		"DeployFrame":                reflect.ValueOf(txtypes.DeployFrame),
		"DynamicFeeTxType":           reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"EntryPoint":                 reflect.ValueOf(&txtypes.EntryPoint).Elem(),
		"ErrInvalidFrameTx":          reflect.ValueOf(&txtypes.ErrInvalidFrameTx).Elem(),
		"ErrInvalidSig":              reflect.ValueOf(&txtypes.ErrInvalidSig).Elem(),
		"ErrMempoolPolicy":           reflect.ValueOf(&txtypes.ErrMempoolPolicy).Elem(),
		"ErrTxTypeNotSupported":      reflect.ValueOf(&txtypes.ErrTxTypeNotSupported).Elem(),
		"ErrUnrecoverableSender":     reflect.ValueOf(&txtypes.ErrUnrecoverableSender).Elem(),
		"ErrUnsignableTx":            reflect.ValueOf(&txtypes.ErrUnsignableTx).Elem(),
		"ExpiryDataLength":           reflect.ValueOf(constant.MakeFromLiteral("8", token.INT, 0)),
		"ExpiryFrame":                reflect.ValueOf(txtypes.ExpiryFrame),
		"ExpiryVerifier":             reflect.ValueOf(&txtypes.ExpiryVerifier).Elem(),
		"FrameBlobSidecarVersion1":   reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"FrameFlagsMask":             reflect.ValueOf(constant.MakeFromLiteral("7", token.INT, 0)),
		"FrameModeDefault":           reflect.ValueOf(txtypes.FrameModeDefault),
		"FrameModeSender":            reflect.ValueOf(txtypes.FrameModeSender),
		"FrameModeVerify":            reflect.ValueOf(txtypes.FrameModeVerify),
		"FrameStatusFailed":          reflect.ValueOf(txtypes.FrameStatusFailed),
		"FrameStatusSkipped":         reflect.ValueOf(txtypes.FrameStatusSkipped),
		"FrameStatusSuccess":         reflect.ValueOf(txtypes.FrameStatusSuccess),
		"FrameTxIntrinsicCost":       reflect.ValueOf(constant.MakeFromLiteral("12000", token.INT, 0)),
		"FrameTxPerFrameCost":        reflect.ValueOf(constant.MakeFromLiteral("475", token.INT, 0)),
		"FrameTxType":                reflect.ValueOf(constant.MakeFromLiteral("6", token.INT, 0)),
		"FromGethReceipt":            reflect.ValueOf(txtypes.FromGethReceipt),
		"FromGethTx":                 reflect.ValueOf(txtypes.FromGethTx),
		"GasPerBlob":                 reflect.ValueOf(constant.MakeFromLiteral("131072", token.INT, 0)),
		"IsTxTypeSupported":          reflect.ValueOf(txtypes.IsTxTypeSupported),
		"LegacyNonceKey":             reflect.ValueOf(&txtypes.LegacyNonceKey).Elem(),
		"LegacyTxType":               reflect.ValueOf(constant.MakeFromLiteral("0", token.INT, 0)),
		"MaxFrames":                  reflect.ValueOf(constant.MakeFromLiteral("64", token.INT, 0)),
		"MaxNonceKeys":               reflect.ValueOf(constant.MakeFromLiteral("16", token.INT, 0)),
		"MaxRecentRootReferences":    reflect.ValueOf(constant.MakeFromLiteral("16", token.INT, 0)),
		"MaxVerifyGas":               reflect.ValueOf(constant.MakeFromLiteral("100000", token.INT, 0)),
		"MaxVerifyStateGas":          reflect.ValueOf(constant.MakeFromLiteral("500000", token.INT, 0)),
		"NewBlobSidecar":             reflect.ValueOf(txtypes.NewBlobSidecar),
		"NewFrameTx":                 reflect.ValueOf(txtypes.NewFrameTx),
		"NewTx":                      reflect.ValueOf(txtypes.NewTx),
		"NonceManager":               reflect.ValueOf(&txtypes.NonceManager).Elem(),
		"OnlyVerifyFrame":            reflect.ValueOf(txtypes.OnlyVerifyFrame),
		"P256Signer":                 reflect.ValueOf(txtypes.P256Signer),
		"ParseDelegation":            reflect.ValueOf(txtypes.ParseDelegation),
		"PayFrame":                   reflect.ValueOf(txtypes.PayFrame),
		"PostOpFrame":                reflect.ValueOf(txtypes.PostOpFrame),
		"ReceiptStatusFailed":        reflect.ValueOf(txtypes.ReceiptStatusFailed),
		"ReceiptStatusSuccessful":    reflect.ValueOf(txtypes.ReceiptStatusSuccessful),
		"RecentRootAddress":          reflect.ValueOf(&txtypes.RecentRootAddress).Elem(),
		"RegisterReceiptDecoder":     reflect.ValueOf(txtypes.RegisterReceiptDecoder),
		"RegisterTxType":             reflect.ValueOf(txtypes.RegisterTxType),
		"RegisteredTxTypes":          reflect.ValueOf(txtypes.RegisteredTxTypes),
		"SelfVerifyFrame":            reflect.ValueOf(txtypes.SelfVerifyFrame),
		"SenderSignature":            reflect.ValueOf(txtypes.SenderSignature),
		"SetCodeTxType":              reflect.ValueOf(constant.MakeFromLiteral("4", token.INT, 0)),
		"SigSchemeArbitrary":         reflect.ValueOf(txtypes.SigSchemeArbitrary),
		"SigSchemeP256":              reflect.ValueOf(txtypes.SigSchemeP256),
		"SigSchemeSecp256k1":         reflect.ValueOf(txtypes.SigSchemeSecp256k1),
		"SignAuthorization":          reflect.ValueOf(txtypes.SignAuthorization),
		"SignTx":                     reflect.ValueOf(txtypes.SignTx),
		"SignerSignature":            reflect.ValueOf(txtypes.SignerSignature),
		"SpeciesDeploy":              reflect.ValueOf(txtypes.SpeciesDeploy),
		"SpeciesExpiryVerify":        reflect.ValueOf(txtypes.SpeciesExpiryVerify),
		"SpeciesOnlyVerify":          reflect.ValueOf(txtypes.SpeciesOnlyVerify),
		"SpeciesOther":               reflect.ValueOf(txtypes.SpeciesOther),
		"SpeciesPay":                 reflect.ValueOf(txtypes.SpeciesPay),
		"SpeciesPostOp":              reflect.ValueOf(txtypes.SpeciesPostOp),
		"SpeciesSelfVerify":          reflect.ValueOf(txtypes.SpeciesSelfVerify),
		"SpeciesUserOp":              reflect.ValueOf(txtypes.SpeciesUserOp),
		"StandardTokenCost":          reflect.ValueOf(constant.MakeFromLiteral("4", token.INT, 0)),
		"StateBytesPerNewAccount":    reflect.ValueOf(constant.MakeFromLiteral("120", token.INT, 0)),
		"TotalCostFloorPerToken":     reflect.ValueOf(constant.MakeFromLiteral("16", token.INT, 0)),
		"TxMaxGasLimit":              reflect.ValueOf(constant.MakeFromLiteral("16777216", token.INT, 0)),
		"TxValueCost":                reflect.ValueOf(constant.MakeFromLiteral("6000", token.INT, 0)),
		"UnmarshalJSONTx":            reflect.ValueOf(txtypes.UnmarshalJSONTx),
		"UserOpFrame":                reflect.ValueOf(txtypes.UserOpFrame),
		"VersionedHashVersionKZG":    reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),

		// type definitions
		"AccessList":           reflect.ValueOf((*txtypes.AccessList)(nil)),
		"AccessListTx":         reflect.ValueOf((*txtypes.AccessListTx)(nil)),
		"AccessListTxData":     reflect.ValueOf((*txtypes.AccessListTxData)(nil)),
		"AccessTuple":          reflect.ValueOf((*txtypes.AccessTuple)(nil)),
		"AuthListTxData":       reflect.ValueOf((*txtypes.AuthListTxData)(nil)),
		"BlobSidecar":          reflect.ValueOf((*txtypes.BlobSidecar)(nil)),
		"BlobTx":               reflect.ValueOf((*txtypes.BlobTx)(nil)),
		"BlobTxData":           reflect.ValueOf((*txtypes.BlobTxData)(nil)),
		"Block":                reflect.ValueOf((*txtypes.Block)(nil)),
		"Bloom":                reflect.ValueOf((*txtypes.Bloom)(nil)),
		"DynamicFeeTx":         reflect.ValueOf((*txtypes.DynamicFeeTx)(nil)),
		"ECDSASignedTx":        reflect.ValueOf((*txtypes.ECDSASignedTx)(nil)),
		"ExplicitSenderTx":     reflect.ValueOf((*txtypes.ExplicitSenderTx)(nil)),
		"Frame":                reflect.ValueOf((*txtypes.Frame)(nil)),
		"FrameFees":            reflect.ValueOf((*txtypes.FrameFees)(nil)),
		"FrameLimits":          reflect.ValueOf((*txtypes.FrameLimits)(nil)),
		"FrameMode":            reflect.ValueOf((*txtypes.FrameMode)(nil)),
		"FrameReceipt":         reflect.ValueOf((*txtypes.FrameReceipt)(nil)),
		"FrameReceiptExtra":    reflect.ValueOf((*txtypes.FrameReceiptExtra)(nil)),
		"FrameSigScheme":       reflect.ValueOf((*txtypes.FrameSigScheme)(nil)),
		"FrameSignature":       reflect.ValueOf((*txtypes.FrameSignature)(nil)),
		"FrameSpecies":         reflect.ValueOf((*txtypes.FrameSpecies)(nil)),
		"FrameTx":              reflect.ValueOf((*txtypes.FrameTx)(nil)),
		"Header":               reflect.ValueOf((*txtypes.Header)(nil)),
		"JSONTxData":           reflect.ValueOf((*txtypes.JSONTxData)(nil)),
		"JSONTxEncoder":        reflect.ValueOf((*txtypes.JSONTxEncoder)(nil)),
		"JSONTxFields":         reflect.ValueOf((*txtypes.JSONTxFields)(nil)),
		"LegacyTx":             reflect.ValueOf((*txtypes.LegacyTx)(nil)),
		"Log":                  reflect.ValueOf((*txtypes.Log)(nil)),
		"NetworkEncodedTx":     reflect.ValueOf((*txtypes.NetworkEncodedTx)(nil)),
		"Receipt":              reflect.ValueOf((*txtypes.Receipt)(nil)),
		"ReceiptDecoder":       reflect.ValueOf((*txtypes.ReceiptDecoder)(nil)),
		"ReceiptExtra":         reflect.ValueOf((*txtypes.ReceiptExtra)(nil)),
		"ReceiptExtraEncoder":  reflect.ValueOf((*txtypes.ReceiptExtraEncoder)(nil)),
		"RecentRootReference":  reflect.ValueOf((*txtypes.RecentRootReference)(nil)),
		"SetCodeAuthorization": reflect.ValueOf((*txtypes.SetCodeAuthorization)(nil)),
		"SetCodeTx":            reflect.ValueOf((*txtypes.SetCodeTx)(nil)),
		"StateGasTxData":       reflect.ValueOf((*txtypes.StateGasTxData)(nil)),
		"Transaction":          reflect.ValueOf((*txtypes.Transaction)(nil)),
		"TxData":               reflect.ValueOf((*txtypes.TxData)(nil)),
		"UnknownTx":            reflect.ValueOf((*txtypes.UnknownTx)(nil)),

		// interface wrapper definitions
		"_AccessListTxData":    reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_AccessListTxData)(nil)),
		"_AuthListTxData":      reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_AuthListTxData)(nil)),
		"_BlobTxData":          reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_BlobTxData)(nil)),
		"_ECDSASignedTx":       reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_ECDSASignedTx)(nil)),
		"_ExplicitSenderTx":    reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_ExplicitSenderTx)(nil)),
		"_JSONTxData":          reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_JSONTxData)(nil)),
		"_JSONTxEncoder":       reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_JSONTxEncoder)(nil)),
		"_NetworkEncodedTx":    reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_NetworkEncodedTx)(nil)),
		"_ReceiptExtra":        reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_ReceiptExtra)(nil)),
		"_ReceiptExtraEncoder": reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_ReceiptExtraEncoder)(nil)),
		"_StateGasTxData":      reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_StateGasTxData)(nil)),
		"_TxData":              reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_TxData)(nil)),
	}
}

// _github_com_ethpandaops_spamoor_txtypes_AccessListTxData is an interface wrapper for AccessListTxData type
type _github_com_ethpandaops_spamoor_txtypes_AccessListTxData struct {
	IValue         interface{}
	WGetAccessList func() txtypes.AccessList
}

func (W _github_com_ethpandaops_spamoor_txtypes_AccessListTxData) GetAccessList() txtypes.AccessList {
	return W.WGetAccessList()
}

// _github_com_ethpandaops_spamoor_txtypes_AuthListTxData is an interface wrapper for AuthListTxData type
type _github_com_ethpandaops_spamoor_txtypes_AuthListTxData struct {
	IValue       interface{}
	WGetAuthList func() []txtypes.SetCodeAuthorization
}

func (W _github_com_ethpandaops_spamoor_txtypes_AuthListTxData) GetAuthList() []txtypes.SetCodeAuthorization {
	return W.WGetAuthList()
}

// _github_com_ethpandaops_spamoor_txtypes_BlobTxData is an interface wrapper for BlobTxData type
type _github_com_ethpandaops_spamoor_txtypes_BlobTxData struct {
	IValue            interface{}
	WGetBlobGasFeeCap func() *big.Int
	WGetBlobHashes    func() []common.Hash
	WGetBlobSidecar   func() *txtypes.BlobSidecar
	WSetBlobSidecar   func(sidecar *txtypes.BlobSidecar)
}

func (W _github_com_ethpandaops_spamoor_txtypes_BlobTxData) GetBlobGasFeeCap() *big.Int {
	return W.WGetBlobGasFeeCap()
}
func (W _github_com_ethpandaops_spamoor_txtypes_BlobTxData) GetBlobHashes() []common.Hash {
	return W.WGetBlobHashes()
}
func (W _github_com_ethpandaops_spamoor_txtypes_BlobTxData) GetBlobSidecar() *txtypes.BlobSidecar {
	return W.WGetBlobSidecar()
}
func (W _github_com_ethpandaops_spamoor_txtypes_BlobTxData) SetBlobSidecar(sidecar *txtypes.BlobSidecar) {
	W.WSetBlobSidecar(sidecar)
}

// _github_com_ethpandaops_spamoor_txtypes_ECDSASignedTx is an interface wrapper for ECDSASignedTx type
type _github_com_ethpandaops_spamoor_txtypes_ECDSASignedTx struct {
	IValue              interface{}
	WGetSignatureValues func() (v *big.Int, r *big.Int, s *big.Int)
	WSetSignatureValues func(chainID *big.Int, v *big.Int, r *big.Int, s *big.Int)
	WSigningHash        func(chainID *big.Int) common.Hash
}

func (W _github_com_ethpandaops_spamoor_txtypes_ECDSASignedTx) GetSignatureValues() (v *big.Int, r *big.Int, s *big.Int) {
	return W.WGetSignatureValues()
}
func (W _github_com_ethpandaops_spamoor_txtypes_ECDSASignedTx) SetSignatureValues(chainID *big.Int, v *big.Int, r *big.Int, s *big.Int) {
	W.WSetSignatureValues(chainID, v, r, s)
}
func (W _github_com_ethpandaops_spamoor_txtypes_ECDSASignedTx) SigningHash(chainID *big.Int) common.Hash {
	return W.WSigningHash(chainID)
}

// _github_com_ethpandaops_spamoor_txtypes_ExplicitSenderTx is an interface wrapper for ExplicitSenderTx type
type _github_com_ethpandaops_spamoor_txtypes_ExplicitSenderTx struct {
	IValue       interface{}
	WGetSender   func() common.Address
	WSignPayload func(chainID *big.Int, key *ecdsa.PrivateKey) error
}

func (W _github_com_ethpandaops_spamoor_txtypes_ExplicitSenderTx) GetSender() common.Address {
	return W.WGetSender()
}
func (W _github_com_ethpandaops_spamoor_txtypes_ExplicitSenderTx) SignPayload(chainID *big.Int, key *ecdsa.PrivateKey) error {
	return W.WSignPayload(chainID, key)
}

// _github_com_ethpandaops_spamoor_txtypes_JSONTxData is an interface wrapper for JSONTxData type
type _github_com_ethpandaops_spamoor_txtypes_JSONTxData struct {
	IValue        interface{}
	WDecodeJSONTx func(fields *txtypes.JSONTxFields) error
}

func (W _github_com_ethpandaops_spamoor_txtypes_JSONTxData) DecodeJSONTx(fields *txtypes.JSONTxFields) error {
	return W.WDecodeJSONTx(fields)
}

// _github_com_ethpandaops_spamoor_txtypes_JSONTxEncoder is an interface wrapper for JSONTxEncoder type
type _github_com_ethpandaops_spamoor_txtypes_JSONTxEncoder struct {
	IValue        interface{}
	WEncodeJSONTx func(fields map[string]any)
}

func (W _github_com_ethpandaops_spamoor_txtypes_JSONTxEncoder) EncodeJSONTx(fields map[string]any) {
	W.WEncodeJSONTx(fields)
}

// _github_com_ethpandaops_spamoor_txtypes_NetworkEncodedTx is an interface wrapper for NetworkEncodedTx type
type _github_com_ethpandaops_spamoor_txtypes_NetworkEncodedTx struct {
	IValue                interface{}
	WEncodeNetworkPayload func(w *bytes.Buffer) error
}

func (W _github_com_ethpandaops_spamoor_txtypes_NetworkEncodedTx) EncodeNetworkPayload(w *bytes.Buffer) error {
	return W.WEncodeNetworkPayload(w)
}

// _github_com_ethpandaops_spamoor_txtypes_ReceiptExtra is an interface wrapper for ReceiptExtra type
type _github_com_ethpandaops_spamoor_txtypes_ReceiptExtra struct {
	IValue         interface{}
	WReceiptTxType func() byte
}

func (W _github_com_ethpandaops_spamoor_txtypes_ReceiptExtra) ReceiptTxType() byte {
	return W.WReceiptTxType()
}

// _github_com_ethpandaops_spamoor_txtypes_ReceiptExtraEncoder is an interface wrapper for ReceiptExtraEncoder type
type _github_com_ethpandaops_spamoor_txtypes_ReceiptExtraEncoder struct {
	IValue             interface{}
	WEncodeReceiptJSON func(fields map[string]any)
}

func (W _github_com_ethpandaops_spamoor_txtypes_ReceiptExtraEncoder) EncodeReceiptJSON(fields map[string]any) {
	W.WEncodeReceiptJSON(fields)
}

// _github_com_ethpandaops_spamoor_txtypes_StateGasTxData is an interface wrapper for StateGasTxData type
type _github_com_ethpandaops_spamoor_txtypes_StateGasTxData struct {
	IValue       interface{}
	WGetStateGas func() uint64
}

func (W _github_com_ethpandaops_spamoor_txtypes_StateGasTxData) GetStateGas() uint64 {
	return W.WGetStateGas()
}

// _github_com_ethpandaops_spamoor_txtypes_TxData is an interface wrapper for TxData type
type _github_com_ethpandaops_spamoor_txtypes_TxData struct {
	IValue         interface{}
	WCopyTx        func() txtypes.TxData
	WDecodePayload func(b []byte) error
	WEncodePayload func(w *bytes.Buffer) error
	WGetChainID    func() *big.Int
	WGetData       func() []byte
	WGetGas        func() uint64
	WGetGasFeeCap  func() *big.Int
	WGetGasPrice   func() *big.Int
	WGetGasTipCap  func() *big.Int
	WGetNonce      func() uint64
	WGetTo         func() *common.Address
	WGetValue      func() *big.Int
	WTxType        func() byte
}

func (W _github_com_ethpandaops_spamoor_txtypes_TxData) CopyTx() txtypes.TxData { return W.WCopyTx() }
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) DecodePayload(b []byte) error {
	return W.WDecodePayload(b)
}
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) EncodePayload(w *bytes.Buffer) error {
	return W.WEncodePayload(w)
}
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetChainID() *big.Int { return W.WGetChainID() }
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetData() []byte      { return W.WGetData() }
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetGas() uint64       { return W.WGetGas() }
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetGasFeeCap() *big.Int {
	return W.WGetGasFeeCap()
}
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetGasPrice() *big.Int {
	return W.WGetGasPrice()
}
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetGasTipCap() *big.Int {
	return W.WGetGasTipCap()
}
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetNonce() uint64       { return W.WGetNonce() }
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetTo() *common.Address { return W.WGetTo() }
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetValue() *big.Int     { return W.WGetValue() }
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) TxType() byte           { return W.WTxType() }
