// Code generated by 'yaegi extract github.com/ethereum/go-ethereum/accounts/abi/bind'. DO NOT EDIT.

package symbols

import (
	"context"
	"github.com/ethereum/go-ethereum"
	"github.com/ethereum/go-ethereum/accounts/abi/bind"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"math/big"
	"reflect"
)

func init() {
	Symbols["github.com/ethereum/go-ethereum/accounts/abi/bind/bind"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Bind":                             reflect.ValueOf(bind.Bind),
		"DeployContract":                   reflect.ValueOf(bind.DeployContract),
		"ErrNoBlockHashState":              reflect.ValueOf(&bind.ErrNoBlockHashState).Elem(),
		"ErrNoChainID":                     reflect.ValueOf(&bind.ErrNoChainID).Elem(),
		"ErrNoCode":                        reflect.ValueOf(&bind.ErrNoCode).Elem(),
		"ErrNoCodeAfterDeploy":             reflect.ValueOf(&bind.ErrNoCodeAfterDeploy).Elem(),
		"ErrNoPendingState":                reflect.ValueOf(&bind.ErrNoPendingState).Elem(),
		"ErrNotAuthorized":                 reflect.ValueOf(&bind.ErrNotAuthorized).Elem(),
		"NewBoundContract":                 reflect.ValueOf(bind.NewBoundContract),
		"NewClefTransactor":                reflect.ValueOf(bind.NewClefTransactor),
		"NewKeyStoreTransactor":            reflect.ValueOf(bind.NewKeyStoreTransactor),
		"NewKeyStoreTransactorWithChainID": reflect.ValueOf(bind.NewKeyStoreTransactorWithChainID),
		"NewKeyedTransactor":               reflect.ValueOf(bind.NewKeyedTransactor),
		"NewKeyedTransactorWithChainID":    reflect.ValueOf(bind.NewKeyedTransactorWithChainID),
		"NewTransactor":                    reflect.ValueOf(bind.NewTransactor),
		"NewTransactorWithChainID":         reflect.ValueOf(bind.NewTransactorWithChainID),
		"WaitDeployed":                     reflect.ValueOf(bind.WaitDeployed),
		"WaitDeployedHash":                 reflect.ValueOf(bind.WaitDeployedHash),
		"WaitMined":                        reflect.ValueOf(bind.WaitMined),
		"WaitMinedHash":                    reflect.ValueOf(bind.WaitMinedHash),

		// type definitions
		"BlockHashContractCaller": reflect.ValueOf((*bind.BlockHashContractCaller)(nil)),
		"BoundContract":           reflect.ValueOf((*bind.BoundContract)(nil)),
		"CallOpts":                reflect.ValueOf((*bind.CallOpts)(nil)),
		"ContractBackend":         reflect.ValueOf((*bind.ContractBackend)(nil)),
		"ContractCaller":          reflect.ValueOf((*bind.ContractCaller)(nil)),
		"ContractFilterer":        reflect.ValueOf((*bind.ContractFilterer)(nil)),
		"ContractTransactor":      reflect.ValueOf((*bind.ContractTransactor)(nil)),
		"DeployBackend":           reflect.ValueOf((*bind.DeployBackend)(nil)),
		"FilterOpts":              reflect.ValueOf((*bind.FilterOpts)(nil)),
		"MetaData":                reflect.ValueOf((*bind.MetaData)(nil)),
		"PendingContractCaller":   reflect.ValueOf((*bind.PendingContractCaller)(nil)),
		"SignerFn":                reflect.ValueOf((*bind.SignerFn)(nil)),
		"TransactOpts":            reflect.ValueOf((*bind.TransactOpts)(nil)),
		"WatchOpts":               reflect.ValueOf((*bind.WatchOpts)(nil)),

		// interface wrapper definitions
		"_BlockHashContractCaller": reflect.ValueOf((*_github_com_ethereum_go_ethereum_accounts_abi_bind_BlockHashContractCaller)(nil)),
		"_ContractBackend":         reflect.ValueOf((*_github_com_ethereum_go_ethereum_accounts_abi_bind_ContractBackend)(nil)),
		"_ContractCaller":          reflect.ValueOf((*_github_com_ethereum_go_ethereum_accounts_abi_bind_ContractCaller)(nil)),
		"_ContractFilterer":        reflect.ValueOf((*_github_com_ethereum_go_ethereum_accounts_abi_bind_ContractFilterer)(nil)),
		"_ContractTransactor":      reflect.ValueOf((*_github_com_ethereum_go_ethereum_accounts_abi_bind_ContractTransactor)(nil)),
		"_DeployBackend":           reflect.ValueOf((*_github_com_ethereum_go_ethereum_accounts_abi_bind_DeployBackend)(nil)),
		"_PendingContractCaller":   reflect.ValueOf((*_github_com_ethereum_go_ethereum_accounts_abi_bind_PendingContractCaller)(nil)),
	}
}

// _github_com_ethereum_go_ethereum_accounts_abi_bind_BlockHashContractCaller is an interface wrapper for BlockHashContractCaller type
type _github_com_ethereum_go_ethereum_accounts_abi_bind_BlockHashContractCaller struct {
	IValue              interface{}
	WCallContractAtHash func(ctx context.Context, call ethereum.CallMsg, blockHash common.Hash) ([]byte, error)
	WCodeAtHash         func(ctx context.Context, contract common.Address, blockHash common.Hash) ([]byte, error)
}

func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_BlockHashContractCaller) CallContractAtHash(ctx context.Context, call ethereum.CallMsg, blockHash common.Hash) ([]byte, error) {
	return W.WCallContractAtHash(ctx, call, blockHash)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_BlockHashContractCaller) CodeAtHash(ctx context.Context, contract common.Address, blockHash common.Hash) ([]byte, error) {
	return W.WCodeAtHash(ctx, contract, blockHash)
}

// _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractBackend is an interface wrapper for ContractBackend type
type _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractBackend struct {
	IValue               interface{}
	WCallContract        func(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error)
	WCodeAt              func(ctx context.Context, contract common.Address, blockNumber *big.Int) ([]byte, error)
	WEstimateGas         func(ctx context.Context, call ethereum.CallMsg) (uint64, error)
	WFilterLogs          func(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error)
	WHeaderByNumber      func(ctx context.Context, number *big.Int) (*types.Header, error)
	WPendingCodeAt       func(ctx context.Context, account common.Address) ([]byte, error)
	WPendingNonceAt      func(ctx context.Context, account common.Address) (uint64, error)
	WSendTransaction     func(ctx context.Context, tx *types.Transaction) error
	WSubscribeFilterLogs func(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error)
	WSuggestGasPrice     func(ctx context.Context) (*big.Int, error)
	WSuggestGasTipCap    func(ctx context.Context) (*big.Int, error)
}

func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractBackend) CallContract(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error) {
	return W.WCallContract(ctx, call, blockNumber)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractBackend) CodeAt(ctx context.Context, contract common.Address, blockNumber *big.Int) ([]byte, error) {
	return W.WCodeAt(ctx, contract, blockNumber)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractBackend) EstimateGas(ctx context.Context, call ethereum.CallMsg) (uint64, error) {
	return W.WEstimateGas(ctx, call)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractBackend) FilterLogs(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error) {
	return W.WFilterLogs(ctx, q)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractBackend) HeaderByNumber(ctx context.Context, number *big.Int) (*types.Header, error) {
	return W.WHeaderByNumber(ctx, number)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractBackend) PendingCodeAt(ctx context.Context, account common.Address) ([]byte, error) {
	return W.WPendingCodeAt(ctx, account)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractBackend) PendingNonceAt(ctx context.Context, account common.Address) (uint64, error) {
	return W.WPendingNonceAt(ctx, account)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractBackend) SendTransaction(ctx context.Context, tx *types.Transaction) error {
	return W.WSendTransaction(ctx, tx)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractBackend) SubscribeFilterLogs(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error) {
	return W.WSubscribeFilterLogs(ctx, q, ch)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractBackend) SuggestGasPrice(ctx context.Context) (*big.Int, error) {
	return W.WSuggestGasPrice(ctx)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractBackend) SuggestGasTipCap(ctx context.Context) (*big.Int, error) {
	return W.WSuggestGasTipCap(ctx)
}

// _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractCaller is an interface wrapper for ContractCaller type
type _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractCaller struct {
	IValue        interface{}
	WCallContract func(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error)
	WCodeAt       func(ctx context.Context, contract common.Address, blockNumber *big.Int) ([]byte, error)
}

func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractCaller) CallContract(ctx context.Context, call ethereum.CallMsg, blockNumber *big.Int) ([]byte, error) {
	return W.WCallContract(ctx, call, blockNumber)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractCaller) CodeAt(ctx context.Context, contract common.Address, blockNumber *big.Int) ([]byte, error) {
	return W.WCodeAt(ctx, contract, blockNumber)
}

// _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractFilterer is an interface wrapper for ContractFilterer type
type _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractFilterer struct {
	IValue               interface{}
	WFilterLogs          func(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error)
	WSubscribeFilterLogs func(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error)
}

func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractFilterer) FilterLogs(ctx context.Context, q ethereum.FilterQuery) ([]types.Log, error) {
	return W.WFilterLogs(ctx, q)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractFilterer) SubscribeFilterLogs(ctx context.Context, q ethereum.FilterQuery, ch chan<- types.Log) (ethereum.Subscription, error) {
	return W.WSubscribeFilterLogs(ctx, q, ch)
}

// _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractTransactor is an interface wrapper for ContractTransactor type
type _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractTransactor struct {
	IValue            interface{}
	WEstimateGas      func(ctx context.Context, call ethereum.CallMsg) (uint64, error)
	WHeaderByNumber   func(ctx context.Context, number *big.Int) (*types.Header, error)
	WPendingCodeAt    func(ctx context.Context, account common.Address) ([]byte, error)
	WPendingNonceAt   func(ctx context.Context, account common.Address) (uint64, error)
	WSendTransaction  func(ctx context.Context, tx *types.Transaction) error
	WSuggestGasPrice  func(ctx context.Context) (*big.Int, error)
	WSuggestGasTipCap func(ctx context.Context) (*big.Int, error)
}

func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractTransactor) EstimateGas(ctx context.Context, call ethereum.CallMsg) (uint64, error) {
	return W.WEstimateGas(ctx, call)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractTransactor) HeaderByNumber(ctx context.Context, number *big.Int) (*types.Header, error) {
	return W.WHeaderByNumber(ctx, number)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractTransactor) PendingCodeAt(ctx context.Context, account common.Address) ([]byte, error) {
	return W.WPendingCodeAt(ctx, account)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractTransactor) PendingNonceAt(ctx context.Context, account common.Address) (uint64, error) {
	return W.WPendingNonceAt(ctx, account)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractTransactor) SendTransaction(ctx context.Context, tx *types.Transaction) error {
	return W.WSendTransaction(ctx, tx)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractTransactor) SuggestGasPrice(ctx context.Context) (*big.Int, error) {
	return W.WSuggestGasPrice(ctx)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_ContractTransactor) SuggestGasTipCap(ctx context.Context) (*big.Int, error) {
	return W.WSuggestGasTipCap(ctx)
}

// _github_com_ethereum_go_ethereum_accounts_abi_bind_DeployBackend is an interface wrapper for DeployBackend type
type _github_com_ethereum_go_ethereum_accounts_abi_bind_DeployBackend struct {
	IValue              interface{}
	WCodeAt             func(ctx context.Context, account common.Address, blockNumber *big.Int) ([]byte, error)
	WTransactionReceipt func(ctx context.Context, txHash common.Hash) (*types.Receipt, error)
}

func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_DeployBackend) CodeAt(ctx context.Context, account common.Address, blockNumber *big.Int) ([]byte, error) {
	return W.WCodeAt(ctx, account, blockNumber)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_DeployBackend) TransactionReceipt(ctx context.Context, txHash common.Hash) (*types.Receipt, error) {
	return W.WTransactionReceipt(ctx, txHash)
}

// _github_com_ethereum_go_ethereum_accounts_abi_bind_PendingContractCaller is an interface wrapper for PendingContractCaller type
type _github_com_ethereum_go_ethereum_accounts_abi_bind_PendingContractCaller struct {
	IValue               interface{}
	WPendingCallContract func(ctx context.Context, call ethereum.CallMsg) ([]byte, error)
	WPendingCodeAt       func(ctx context.Context, contract common.Address) ([]byte, error)
}

func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_PendingContractCaller) PendingCallContract(ctx context.Context, call ethereum.CallMsg) ([]byte, error) {
	return W.WPendingCallContract(ctx, call)
}
func (W _github_com_ethereum_go_ethereum_accounts_abi_bind_PendingContractCaller) PendingCodeAt(ctx context.Context, contract common.Address) ([]byte, error) {
	return W.WPendingCodeAt(ctx, contract)
}
