// Code generated by 'yaegi extract github.com/ethpandaops/spamoor/txtypes'. DO NOT EDIT.

package symbols

import (
	"bytes"
	"crypto/ecdsa"
	"go/constant"
	"go/token"
	"math/big"
	"reflect"

	"github.com/ethereum/go-ethereum/common"

	"github.com/ethpandaops/spamoor/txtypes"
)

func init() {
	Symbols["github.com/ethpandaops/spamoor/txtypes/txtypes"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AccessListTxType":        reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"AddressToDelegation":     reflect.ValueOf(txtypes.AddressToDelegation),
		"BlobSidecarVersion0":     reflect.ValueOf(txtypes.BlobSidecarVersion0),
		"BlobSidecarVersion1":     reflect.ValueOf(txtypes.BlobSidecarVersion1),
		"BlobTxType":              reflect.ValueOf(constant.MakeFromLiteral("3", token.INT, 0)),
		"DecodeTx":                reflect.ValueOf(txtypes.DecodeTx),
		"DelegationPrefix":        reflect.ValueOf(&txtypes.DelegationPrefix).Elem(),
		"DynamicFeeTxType":        reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"ErrInvalidSig":           reflect.ValueOf(&txtypes.ErrInvalidSig).Elem(),
		"ErrTxTypeNotSupported":   reflect.ValueOf(&txtypes.ErrTxTypeNotSupported).Elem(),
		"ErrUnrecoverableSender":  reflect.ValueOf(&txtypes.ErrUnrecoverableSender).Elem(),
		"ErrUnsignableTx":         reflect.ValueOf(&txtypes.ErrUnsignableTx).Elem(),
		"FromGethReceipt":         reflect.ValueOf(txtypes.FromGethReceipt),
		"FromGethTx":              reflect.ValueOf(txtypes.FromGethTx),
		"IsTxTypeSupported":       reflect.ValueOf(txtypes.IsTxTypeSupported),
		"LegacyTxType":            reflect.ValueOf(constant.MakeFromLiteral("0", token.INT, 0)),
		"NewBlobSidecar":          reflect.ValueOf(txtypes.NewBlobSidecar),
		"NewTx":                   reflect.ValueOf(txtypes.NewTx),
		"ParseDelegation":         reflect.ValueOf(txtypes.ParseDelegation),
		"ReceiptStatusFailed":     reflect.ValueOf(txtypes.ReceiptStatusFailed),
		"ReceiptStatusSuccessful": reflect.ValueOf(txtypes.ReceiptStatusSuccessful),
		"RegisterReceiptDecoder":  reflect.ValueOf(txtypes.RegisterReceiptDecoder),
		"RegisterTxType":          reflect.ValueOf(txtypes.RegisterTxType),
		"RegisteredTxTypes":       reflect.ValueOf(txtypes.RegisteredTxTypes),
		"SetCodeTxType":           reflect.ValueOf(constant.MakeFromLiteral("4", token.INT, 0)),
		"SignAuthorization":       reflect.ValueOf(txtypes.SignAuthorization),
		"SignTx":                  reflect.ValueOf(txtypes.SignTx),
		"UnmarshalJSONTx":         reflect.ValueOf(txtypes.UnmarshalJSONTx),

		// type definitions
		"AccessList":           reflect.ValueOf((*txtypes.AccessList)(nil)),
		"AccessListTx":         reflect.ValueOf((*txtypes.AccessListTx)(nil)),
		"AccessListTxData":     reflect.ValueOf((*txtypes.AccessListTxData)(nil)),
		"AccessTuple":          reflect.ValueOf((*txtypes.AccessTuple)(nil)),
		"AuthListTxData":       reflect.ValueOf((*txtypes.AuthListTxData)(nil)),
		"BlobSidecar":          reflect.ValueOf((*txtypes.BlobSidecar)(nil)),
		"BlobTx":               reflect.ValueOf((*txtypes.BlobTx)(nil)),
		"BlobTxData":           reflect.ValueOf((*txtypes.BlobTxData)(nil)),
		"Block":                reflect.ValueOf((*txtypes.Block)(nil)),
		"DynamicFeeTx":         reflect.ValueOf((*txtypes.DynamicFeeTx)(nil)),
		"ECDSASignedTx":        reflect.ValueOf((*txtypes.ECDSASignedTx)(nil)),
		"ExplicitSenderTx":     reflect.ValueOf((*txtypes.ExplicitSenderTx)(nil)),
		"Header":               reflect.ValueOf((*txtypes.Header)(nil)),
		"JSONTxData":           reflect.ValueOf((*txtypes.JSONTxData)(nil)),
		"JSONTxFields":         reflect.ValueOf((*txtypes.JSONTxFields)(nil)),
		"LegacyTx":             reflect.ValueOf((*txtypes.LegacyTx)(nil)),
		"Log":                  reflect.ValueOf((*txtypes.Log)(nil)),
		"NetworkEncodedTx":     reflect.ValueOf((*txtypes.NetworkEncodedTx)(nil)),
		"Receipt":              reflect.ValueOf((*txtypes.Receipt)(nil)),
		"ReceiptDecoder":       reflect.ValueOf((*txtypes.ReceiptDecoder)(nil)),
		"ReceiptExtra":         reflect.ValueOf((*txtypes.ReceiptExtra)(nil)),
		"SetCodeAuthorization": reflect.ValueOf((*txtypes.SetCodeAuthorization)(nil)),
		"SetCodeTx":            reflect.ValueOf((*txtypes.SetCodeTx)(nil)),
		"StateGasTxData":       reflect.ValueOf((*txtypes.StateGasTxData)(nil)),
		"Transaction":          reflect.ValueOf((*txtypes.Transaction)(nil)),
		"TxData":               reflect.ValueOf((*txtypes.TxData)(nil)),
		"UnknownTx":            reflect.ValueOf((*txtypes.UnknownTx)(nil)),

		// interface wrapper definitions
		"_AccessListTxData": reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_AccessListTxData)(nil)),
		"_AuthListTxData":   reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_AuthListTxData)(nil)),
		"_BlobTxData":       reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_BlobTxData)(nil)),
		"_ECDSASignedTx":    reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_ECDSASignedTx)(nil)),
		"_ExplicitSenderTx": reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_ExplicitSenderTx)(nil)),
		"_JSONTxData":       reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_JSONTxData)(nil)),
		"_NetworkEncodedTx": reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_NetworkEncodedTx)(nil)),
		"_ReceiptExtra":     reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_ReceiptExtra)(nil)),
		"_StateGasTxData":   reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_StateGasTxData)(nil)),
		"_TxData":           reflect.ValueOf((*_github_com_ethpandaops_spamoor_txtypes_TxData)(nil)),
	}
}

// _github_com_ethpandaops_spamoor_txtypes_AccessListTxData is an interface wrapper for AccessListTxData type
type _github_com_ethpandaops_spamoor_txtypes_AccessListTxData struct {
	IValue         interface{}
	WGetAccessList func() txtypes.AccessList
}

func (W _github_com_ethpandaops_spamoor_txtypes_AccessListTxData) GetAccessList() txtypes.AccessList {
	return W.WGetAccessList()
}

// _github_com_ethpandaops_spamoor_txtypes_AuthListTxData is an interface wrapper for AuthListTxData type
type _github_com_ethpandaops_spamoor_txtypes_AuthListTxData struct {
	IValue       interface{}
	WGetAuthList func() []txtypes.SetCodeAuthorization
}

func (W _github_com_ethpandaops_spamoor_txtypes_AuthListTxData) GetAuthList() []txtypes.SetCodeAuthorization {
	return W.WGetAuthList()
}

// _github_com_ethpandaops_spamoor_txtypes_BlobTxData is an interface wrapper for BlobTxData type
type _github_com_ethpandaops_spamoor_txtypes_BlobTxData struct {
	IValue            interface{}
	WGetBlobGasFeeCap func() *big.Int
	WGetBlobHashes    func() []common.Hash
	WGetBlobSidecar   func() *txtypes.BlobSidecar
	WSetBlobSidecar   func(sidecar *txtypes.BlobSidecar)
}

func (W _github_com_ethpandaops_spamoor_txtypes_BlobTxData) GetBlobGasFeeCap() *big.Int {
	return W.WGetBlobGasFeeCap()
}
func (W _github_com_ethpandaops_spamoor_txtypes_BlobTxData) GetBlobHashes() []common.Hash {
	return W.WGetBlobHashes()
}
func (W _github_com_ethpandaops_spamoor_txtypes_BlobTxData) GetBlobSidecar() *txtypes.BlobSidecar {
	return W.WGetBlobSidecar()
}
func (W _github_com_ethpandaops_spamoor_txtypes_BlobTxData) SetBlobSidecar(sidecar *txtypes.BlobSidecar) {
	W.WSetBlobSidecar(sidecar)
}

// _github_com_ethpandaops_spamoor_txtypes_ECDSASignedTx is an interface wrapper for ECDSASignedTx type
type _github_com_ethpandaops_spamoor_txtypes_ECDSASignedTx struct {
	IValue              interface{}
	WGetSignatureValues func() (v *big.Int, r *big.Int, s *big.Int)
	WSetSignatureValues func(chainID *big.Int, v *big.Int, r *big.Int, s *big.Int)
	WSigningHash        func(chainID *big.Int) common.Hash
}

func (W _github_com_ethpandaops_spamoor_txtypes_ECDSASignedTx) GetSignatureValues() (v *big.Int, r *big.Int, s *big.Int) {
	return W.WGetSignatureValues()
}
func (W _github_com_ethpandaops_spamoor_txtypes_ECDSASignedTx) SetSignatureValues(chainID *big.Int, v *big.Int, r *big.Int, s *big.Int) {
	W.WSetSignatureValues(chainID, v, r, s)
}
func (W _github_com_ethpandaops_spamoor_txtypes_ECDSASignedTx) SigningHash(chainID *big.Int) common.Hash {
	return W.WSigningHash(chainID)
}

// _github_com_ethpandaops_spamoor_txtypes_ExplicitSenderTx is an interface wrapper for ExplicitSenderTx type
type _github_com_ethpandaops_spamoor_txtypes_ExplicitSenderTx struct {
	IValue       interface{}
	WGetSender   func() common.Address
	WSignPayload func(chainID *big.Int, key *ecdsa.PrivateKey) error
}

func (W _github_com_ethpandaops_spamoor_txtypes_ExplicitSenderTx) GetSender() common.Address {
	return W.WGetSender()
}
func (W _github_com_ethpandaops_spamoor_txtypes_ExplicitSenderTx) SignPayload(chainID *big.Int, key *ecdsa.PrivateKey) error {
	return W.WSignPayload(chainID, key)
}

// _github_com_ethpandaops_spamoor_txtypes_JSONTxData is an interface wrapper for JSONTxData type
type _github_com_ethpandaops_spamoor_txtypes_JSONTxData struct {
	IValue        interface{}
	WDecodeJSONTx func(fields *txtypes.JSONTxFields) error
}

func (W _github_com_ethpandaops_spamoor_txtypes_JSONTxData) DecodeJSONTx(fields *txtypes.JSONTxFields) error {
	return W.WDecodeJSONTx(fields)
}

// _github_com_ethpandaops_spamoor_txtypes_NetworkEncodedTx is an interface wrapper for NetworkEncodedTx type
type _github_com_ethpandaops_spamoor_txtypes_NetworkEncodedTx struct {
	IValue                interface{}
	WEncodeNetworkPayload func(w *bytes.Buffer) error
}

func (W _github_com_ethpandaops_spamoor_txtypes_NetworkEncodedTx) EncodeNetworkPayload(w *bytes.Buffer) error {
	return W.WEncodeNetworkPayload(w)
}

// _github_com_ethpandaops_spamoor_txtypes_ReceiptExtra is an interface wrapper for ReceiptExtra type
type _github_com_ethpandaops_spamoor_txtypes_ReceiptExtra struct {
	IValue         interface{}
	WReceiptTxType func() byte
}

func (W _github_com_ethpandaops_spamoor_txtypes_ReceiptExtra) ReceiptTxType() byte {
	return W.WReceiptTxType()
}

// _github_com_ethpandaops_spamoor_txtypes_StateGasTxData is an interface wrapper for StateGasTxData type
type _github_com_ethpandaops_spamoor_txtypes_StateGasTxData struct {
	IValue       interface{}
	WGetStateGas func() uint64
}

func (W _github_com_ethpandaops_spamoor_txtypes_StateGasTxData) GetStateGas() uint64 {
	return W.WGetStateGas()
}

// _github_com_ethpandaops_spamoor_txtypes_TxData is an interface wrapper for TxData type
type _github_com_ethpandaops_spamoor_txtypes_TxData struct {
	IValue         interface{}
	WCopyTx        func() txtypes.TxData
	WDecodePayload func(b []byte) error
	WEncodePayload func(w *bytes.Buffer) error
	WGetChainID    func() *big.Int
	WGetData       func() []byte
	WGetGas        func() uint64
	WGetGasFeeCap  func() *big.Int
	WGetGasPrice   func() *big.Int
	WGetGasTipCap  func() *big.Int
	WGetNonce      func() uint64
	WGetTo         func() *common.Address
	WGetValue      func() *big.Int
	WTxType        func() byte
}

func (W _github_com_ethpandaops_spamoor_txtypes_TxData) CopyTx() txtypes.TxData { return W.WCopyTx() }
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) DecodePayload(b []byte) error {
	return W.WDecodePayload(b)
}
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) EncodePayload(w *bytes.Buffer) error {
	return W.WEncodePayload(w)
}
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetChainID() *big.Int { return W.WGetChainID() }
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetData() []byte      { return W.WGetData() }
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetGas() uint64       { return W.WGetGas() }
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetGasFeeCap() *big.Int {
	return W.WGetGasFeeCap()
}
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetGasPrice() *big.Int {
	return W.WGetGasPrice()
}
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetGasTipCap() *big.Int {
	return W.WGetGasTipCap()
}
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetNonce() uint64       { return W.WGetNonce() }
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetTo() *common.Address { return W.WGetTo() }
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) GetValue() *big.Int     { return W.WGetValue() }
func (W _github_com_ethpandaops_spamoor_txtypes_TxData) TxType() byte           { return W.WTxType() }
