// Code generated by 'yaegi extract github.com/spf13/pflag'. DO NOT EDIT.

package symbols

import (
	"github.com/spf13/pflag"
	"reflect"
)

func init() {
	Symbols["github.com/spf13/pflag/pflag"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"Arg":                reflect.ValueOf(pflag.Arg),
		"Args":               reflect.ValueOf(pflag.Args),
		"Bool":               reflect.ValueOf(pflag.Bool),
		"BoolFunc":           reflect.ValueOf(pflag.BoolFunc),
		"BoolFuncP":          reflect.ValueOf(pflag.BoolFuncP),
		"BoolP":              reflect.ValueOf(pflag.BoolP),
		"BoolSlice":          reflect.ValueOf(pflag.BoolSlice),
		"BoolSliceP":         reflect.ValueOf(pflag.BoolSliceP),
		"BoolSliceVar":       reflect.ValueOf(pflag.BoolSliceVar),
		"BoolSliceVarP":      reflect.ValueOf(pflag.BoolSliceVarP),
		"BoolVar":            reflect.ValueOf(pflag.BoolVar),
		"BoolVarP":           reflect.ValueOf(pflag.BoolVarP),
		"BytesBase64":        reflect.ValueOf(pflag.BytesBase64),
		"BytesBase64P":       reflect.ValueOf(pflag.BytesBase64P),
		"BytesBase64Var":     reflect.ValueOf(pflag.BytesBase64Var),
		"BytesBase64VarP":    reflect.ValueOf(pflag.BytesBase64VarP),
		"BytesHex":           reflect.ValueOf(pflag.BytesHex),
		"BytesHexP":          reflect.ValueOf(pflag.BytesHexP),
		"BytesHexVar":        reflect.ValueOf(pflag.BytesHexVar),
		"BytesHexVarP":       reflect.ValueOf(pflag.BytesHexVarP),
		"CommandLine":        reflect.ValueOf(&pflag.CommandLine).Elem(),
		"ContinueOnError":    reflect.ValueOf(pflag.ContinueOnError),
		"Count":              reflect.ValueOf(pflag.Count),
		"CountP":             reflect.ValueOf(pflag.CountP),
		"CountVar":           reflect.ValueOf(pflag.CountVar),
		"CountVarP":          reflect.ValueOf(pflag.CountVarP),
		"Duration":           reflect.ValueOf(pflag.Duration),
		"DurationP":          reflect.ValueOf(pflag.DurationP),
		"DurationSlice":      reflect.ValueOf(pflag.DurationSlice),
		"DurationSliceP":     reflect.ValueOf(pflag.DurationSliceP),
		"DurationSliceVar":   reflect.ValueOf(pflag.DurationSliceVar),
		"DurationSliceVarP":  reflect.ValueOf(pflag.DurationSliceVarP),
		"DurationVar":        reflect.ValueOf(pflag.DurationVar),
		"DurationVarP":       reflect.ValueOf(pflag.DurationVarP),
		"ErrHelp":            reflect.ValueOf(&pflag.ErrHelp).Elem(),
		"ExitOnError":        reflect.ValueOf(pflag.ExitOnError),
		"Float32":            reflect.ValueOf(pflag.Float32),
		"Float32P":           reflect.ValueOf(pflag.Float32P),
		"Float32Slice":       reflect.ValueOf(pflag.Float32Slice),
		"Float32SliceP":      reflect.ValueOf(pflag.Float32SliceP),
		"Float32SliceVar":    reflect.ValueOf(pflag.Float32SliceVar),
		"Float32SliceVarP":   reflect.ValueOf(pflag.Float32SliceVarP),
		"Float32Var":         reflect.ValueOf(pflag.Float32Var),
		"Float32VarP":        reflect.ValueOf(pflag.Float32VarP),
		"Float64":            reflect.ValueOf(pflag.Float64),
		"Float64P":           reflect.ValueOf(pflag.Float64P),
		"Float64Slice":       reflect.ValueOf(pflag.Float64Slice),
		"Float64SliceP":      reflect.ValueOf(pflag.Float64SliceP),
		"Float64SliceVar":    reflect.ValueOf(pflag.Float64SliceVar),
		"Float64SliceVarP":   reflect.ValueOf(pflag.Float64SliceVarP),
		"Float64Var":         reflect.ValueOf(pflag.Float64Var),
		"Float64VarP":        reflect.ValueOf(pflag.Float64VarP),
		"Func":               reflect.ValueOf(pflag.Func),
		"FuncP":              reflect.ValueOf(pflag.FuncP),
		"IP":                 reflect.ValueOf(pflag.IP),
		"IPMask":             reflect.ValueOf(pflag.IPMask),
		"IPMaskP":            reflect.ValueOf(pflag.IPMaskP),
		"IPMaskVar":          reflect.ValueOf(pflag.IPMaskVar),
		"IPMaskVarP":         reflect.ValueOf(pflag.IPMaskVarP),
		"IPNet":              reflect.ValueOf(pflag.IPNet),
		"IPNetP":             reflect.ValueOf(pflag.IPNetP),
		"IPNetSlice":         reflect.ValueOf(pflag.IPNetSlice),
		"IPNetSliceP":        reflect.ValueOf(pflag.IPNetSliceP),
		"IPNetSliceVar":      reflect.ValueOf(pflag.IPNetSliceVar),
		"IPNetSliceVarP":     reflect.ValueOf(pflag.IPNetSliceVarP),
		"IPNetVar":           reflect.ValueOf(pflag.IPNetVar),
		"IPNetVarP":          reflect.ValueOf(pflag.IPNetVarP),
		"IPP":                reflect.ValueOf(pflag.IPP),
		"IPSlice":            reflect.ValueOf(pflag.IPSlice),
		"IPSliceP":           reflect.ValueOf(pflag.IPSliceP),
		"IPSliceVar":         reflect.ValueOf(pflag.IPSliceVar),
		"IPSliceVarP":        reflect.ValueOf(pflag.IPSliceVarP),
		"IPVar":              reflect.ValueOf(pflag.IPVar),
		"IPVarP":             reflect.ValueOf(pflag.IPVarP),
		"Int":                reflect.ValueOf(pflag.Int),
		"Int16":              reflect.ValueOf(pflag.Int16),
		"Int16P":             reflect.ValueOf(pflag.Int16P),
		"Int16Var":           reflect.ValueOf(pflag.Int16Var),
		"Int16VarP":          reflect.ValueOf(pflag.Int16VarP),
		"Int32":              reflect.ValueOf(pflag.Int32),
		"Int32P":             reflect.ValueOf(pflag.Int32P),
		"Int32Slice":         reflect.ValueOf(pflag.Int32Slice),
		"Int32SliceP":        reflect.ValueOf(pflag.Int32SliceP),
		"Int32SliceVar":      reflect.ValueOf(pflag.Int32SliceVar),
		"Int32SliceVarP":     reflect.ValueOf(pflag.Int32SliceVarP),
		"Int32Var":           reflect.ValueOf(pflag.Int32Var),
		"Int32VarP":          reflect.ValueOf(pflag.Int32VarP),
		"Int64":              reflect.ValueOf(pflag.Int64),
		"Int64P":             reflect.ValueOf(pflag.Int64P),
		"Int64Slice":         reflect.ValueOf(pflag.Int64Slice),
		"Int64SliceP":        reflect.ValueOf(pflag.Int64SliceP),
		"Int64SliceVar":      reflect.ValueOf(pflag.Int64SliceVar),
		"Int64SliceVarP":     reflect.ValueOf(pflag.Int64SliceVarP),
		"Int64Var":           reflect.ValueOf(pflag.Int64Var),
		"Int64VarP":          reflect.ValueOf(pflag.Int64VarP),
		"Int8":               reflect.ValueOf(pflag.Int8),
		"Int8P":              reflect.ValueOf(pflag.Int8P),
		"Int8Var":            reflect.ValueOf(pflag.Int8Var),
		"Int8VarP":           reflect.ValueOf(pflag.Int8VarP),
		"IntP":               reflect.ValueOf(pflag.IntP),
		"IntSlice":           reflect.ValueOf(pflag.IntSlice),
		"IntSliceP":          reflect.ValueOf(pflag.IntSliceP),
		"IntSliceVar":        reflect.ValueOf(pflag.IntSliceVar),
		"IntSliceVarP":       reflect.ValueOf(pflag.IntSliceVarP),
		"IntVar":             reflect.ValueOf(pflag.IntVar),
		"IntVarP":            reflect.ValueOf(pflag.IntVarP),
		"Lookup":             reflect.ValueOf(pflag.Lookup),
		"NArg":               reflect.ValueOf(pflag.NArg),
		"NFlag":              reflect.ValueOf(pflag.NFlag),
		"NewFlagSet":         reflect.ValueOf(pflag.NewFlagSet),
		"PFlagFromGoFlag":    reflect.ValueOf(pflag.PFlagFromGoFlag),
		"PanicOnError":       reflect.ValueOf(pflag.PanicOnError),
		"Parse":              reflect.ValueOf(pflag.Parse),
		"ParseAll":           reflect.ValueOf(pflag.ParseAll),
		"ParseIPv4Mask":      reflect.ValueOf(pflag.ParseIPv4Mask),
		"ParseSkippedFlags":  reflect.ValueOf(pflag.ParseSkippedFlags),
		"Parsed":             reflect.ValueOf(pflag.Parsed),
		"PrintDefaults":      reflect.ValueOf(pflag.PrintDefaults),
		"Set":                reflect.ValueOf(pflag.Set),
		"SetInterspersed":    reflect.ValueOf(pflag.SetInterspersed),
		"ShorthandLookup":    reflect.ValueOf(pflag.ShorthandLookup),
		"String":             reflect.ValueOf(pflag.String),
		"StringArray":        reflect.ValueOf(pflag.StringArray),
		"StringArrayP":       reflect.ValueOf(pflag.StringArrayP),
		"StringArrayVar":     reflect.ValueOf(pflag.StringArrayVar),
		"StringArrayVarP":    reflect.ValueOf(pflag.StringArrayVarP),
		"StringP":            reflect.ValueOf(pflag.StringP),
		"StringSlice":        reflect.ValueOf(pflag.StringSlice),
		"StringSliceP":       reflect.ValueOf(pflag.StringSliceP),
		"StringSliceVar":     reflect.ValueOf(pflag.StringSliceVar),
		"StringSliceVarP":    reflect.ValueOf(pflag.StringSliceVarP),
		"StringToInt":        reflect.ValueOf(pflag.StringToInt),
		"StringToInt64":      reflect.ValueOf(pflag.StringToInt64),
		"StringToInt64P":     reflect.ValueOf(pflag.StringToInt64P),
		"StringToInt64Var":   reflect.ValueOf(pflag.StringToInt64Var),
		"StringToInt64VarP":  reflect.ValueOf(pflag.StringToInt64VarP),
		"StringToIntP":       reflect.ValueOf(pflag.StringToIntP),
		"StringToIntVar":     reflect.ValueOf(pflag.StringToIntVar),
		"StringToIntVarP":    reflect.ValueOf(pflag.StringToIntVarP),
		"StringToString":     reflect.ValueOf(pflag.StringToString),
		"StringToStringP":    reflect.ValueOf(pflag.StringToStringP),
		"StringToStringVar":  reflect.ValueOf(pflag.StringToStringVar),
		"StringToStringVarP": reflect.ValueOf(pflag.StringToStringVarP),
		"StringVar":          reflect.ValueOf(pflag.StringVar),
		"StringVarP":         reflect.ValueOf(pflag.StringVarP),
		"TextVar":            reflect.ValueOf(pflag.TextVar),
		"TextVarP":           reflect.ValueOf(pflag.TextVarP),
		"Time":               reflect.ValueOf(pflag.Time),
		"TimeP":              reflect.ValueOf(pflag.TimeP),
		"TimeVar":            reflect.ValueOf(pflag.TimeVar),
		"TimeVarP":           reflect.ValueOf(pflag.TimeVarP),
		"Uint":               reflect.ValueOf(pflag.Uint),
		"Uint16":             reflect.ValueOf(pflag.Uint16),
		"Uint16P":            reflect.ValueOf(pflag.Uint16P),
		"Uint16Var":          reflect.ValueOf(pflag.Uint16Var),
		"Uint16VarP":         reflect.ValueOf(pflag.Uint16VarP),
		"Uint32":             reflect.ValueOf(pflag.Uint32),
		"Uint32P":            reflect.ValueOf(pflag.Uint32P),
		"Uint32Var":          reflect.ValueOf(pflag.Uint32Var),
		"Uint32VarP":         reflect.ValueOf(pflag.Uint32VarP),
		"Uint64":             reflect.ValueOf(pflag.Uint64),
		"Uint64P":            reflect.ValueOf(pflag.Uint64P),
		"Uint64Var":          reflect.ValueOf(pflag.Uint64Var),
		"Uint64VarP":         reflect.ValueOf(pflag.Uint64VarP),
		"Uint8":              reflect.ValueOf(pflag.Uint8),
		"Uint8P":             reflect.ValueOf(pflag.Uint8P),
		"Uint8Var":           reflect.ValueOf(pflag.Uint8Var),
		"Uint8VarP":          reflect.ValueOf(pflag.Uint8VarP),
		"UintP":              reflect.ValueOf(pflag.UintP),
		"UintSlice":          reflect.ValueOf(pflag.UintSlice),
		"UintSliceP":         reflect.ValueOf(pflag.UintSliceP),
		"UintSliceVar":       reflect.ValueOf(pflag.UintSliceVar),
		"UintSliceVarP":      reflect.ValueOf(pflag.UintSliceVarP),
		"UintVar":            reflect.ValueOf(pflag.UintVar),
		"UintVarP":           reflect.ValueOf(pflag.UintVarP),
		"UnquoteUsage":       reflect.ValueOf(pflag.UnquoteUsage),
		"Usage":              reflect.ValueOf(&pflag.Usage).Elem(),
		"Var":                reflect.ValueOf(pflag.Var),
		"VarP":               reflect.ValueOf(pflag.VarP),
		"Visit":              reflect.ValueOf(pflag.Visit),
		"VisitAll":           reflect.ValueOf(pflag.VisitAll),

		// type definitions
		"ErrorHandling":        reflect.ValueOf((*pflag.ErrorHandling)(nil)),
		"Flag":                 reflect.ValueOf((*pflag.Flag)(nil)),
		"FlagSet":              reflect.ValueOf((*pflag.FlagSet)(nil)),
		"InvalidSyntaxError":   reflect.ValueOf((*pflag.InvalidSyntaxError)(nil)),
		"InvalidValueError":    reflect.ValueOf((*pflag.InvalidValueError)(nil)),
		"NormalizedName":       reflect.ValueOf((*pflag.NormalizedName)(nil)),
		"NotExistError":        reflect.ValueOf((*pflag.NotExistError)(nil)),
		"ParseErrorsAllowlist": reflect.ValueOf((*pflag.ParseErrorsAllowlist)(nil)),
		"ParseErrorsWhitelist": reflect.ValueOf((*pflag.ParseErrorsWhitelist)(nil)),
		"SliceValue":           reflect.ValueOf((*pflag.SliceValue)(nil)),
		"Value":                reflect.ValueOf((*pflag.Value)(nil)),
		"ValueRequiredError":   reflect.ValueOf((*pflag.ValueRequiredError)(nil)),

		// interface wrapper definitions
		"_SliceValue": reflect.ValueOf((*_github_com_spf13_pflag_SliceValue)(nil)),
		"_Value":      reflect.ValueOf((*_github_com_spf13_pflag_Value)(nil)),
	}
}

// _github_com_spf13_pflag_SliceValue is an interface wrapper for SliceValue type
type _github_com_spf13_pflag_SliceValue struct {
	IValue    interface{}
	WAppend   func(a0 string) error
	WGetSlice func() []string
	WReplace  func(a0 []string) error
}

func (W _github_com_spf13_pflag_SliceValue) Append(a0 string) error {
	return W.WAppend(a0)
}
func (W _github_com_spf13_pflag_SliceValue) GetSlice() []string {
	return W.WGetSlice()
}
func (W _github_com_spf13_pflag_SliceValue) Replace(a0 []string) error {
	return W.WReplace(a0)
}

// _github_com_spf13_pflag_Value is an interface wrapper for Value type
type _github_com_spf13_pflag_Value struct {
	IValue  interface{}
	WSet    func(a0 string) error
	WString func() string
	WType   func() string
}

func (W _github_com_spf13_pflag_Value) Set(a0 string) error {
	return W.WSet(a0)
}
func (W _github_com_spf13_pflag_Value) String() string {
	if W.WString == nil {
		return ""
	}
	return W.WString()
}
func (W _github_com_spf13_pflag_Value) Type() string {
	return W.WType()
}
