// Code generated by 'yaegi extract github.com/ethpandaops/spamoor/txbuilder'. DO NOT EDIT.

package loader

import (
	"github.com/ethpandaops/spamoor/txbuilder"
	"reflect"
)

func init() {
	Symbols["github.com/ethpandaops/spamoor/txbuilder/txbuilder"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AccessListTx":       reflect.ValueOf(txbuilder.AccessListTx),
		"BuildBlobTx":        reflect.ValueOf(txbuilder.BuildBlobTx),
		"DynFeeTx":           reflect.ValueOf(txbuilder.DynFeeTx),
		"EncodeBlob":         reflect.ValueOf(txbuilder.EncodeBlob),
		"LegacyTx":           reflect.ValueOf(txbuilder.LegacyTx),
		"ParseBlobRefsBytes": reflect.ValueOf(txbuilder.ParseBlobRefsBytes),
		"SetCodeTx":          reflect.ValueOf(txbuilder.SetCodeTx),

		// type definitions
		"BlobCommitment": reflect.ValueOf((*txbuilder.BlobCommitment)(nil)),
		"TxMetadata":     reflect.ValueOf((*txbuilder.TxMetadata)(nil)),
	}
}
