// Code generated by 'yaegi extract github.com/ethereum/go-ethereum/accounts/abi'. DO NOT EDIT.

package loader

import (
	"github.com/ethereum/go-ethereum/accounts/abi"
	"reflect"
)

func init() {
	Symbols["github.com/ethereum/go-ethereum/accounts/abi/abi"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AddressTy":           reflect.ValueOf(abi.AddressTy),
		"ArrayTy":             reflect.ValueOf(abi.ArrayTy),
		"BoolTy":              reflect.ValueOf(abi.BoolTy),
		"BytesTy":             reflect.ValueOf(abi.BytesTy),
		"Constructor":         reflect.ValueOf(abi.Constructor),
		"ConvertType":         reflect.ValueOf(abi.ConvertType),
		"Fallback":            reflect.ValueOf(abi.Fallback),
		"FixedBytesTy":        reflect.ValueOf(abi.FixedBytesTy),
		"FixedPointTy":        reflect.ValueOf(abi.FixedPointTy),
		"Function":            reflect.ValueOf(abi.Function),
		"FunctionTy":          reflect.ValueOf(abi.FunctionTy),
		"HashTy":              reflect.ValueOf(abi.HashTy),
		"IntTy":               reflect.ValueOf(abi.IntTy),
		"JSON":                reflect.ValueOf(abi.JSON),
		"MakeTopics":          reflect.ValueOf(abi.MakeTopics),
		"MaxInt256":           reflect.ValueOf(&abi.MaxInt256).Elem(),
		"MaxUint256":          reflect.ValueOf(&abi.MaxUint256).Elem(),
		"NewError":            reflect.ValueOf(abi.NewError),
		"NewEvent":            reflect.ValueOf(abi.NewEvent),
		"NewMethod":           reflect.ValueOf(abi.NewMethod),
		"NewType":             reflect.ValueOf(abi.NewType),
		"ParseSelector":       reflect.ValueOf(abi.ParseSelector),
		"ParseTopics":         reflect.ValueOf(abi.ParseTopics),
		"ParseTopicsIntoMap":  reflect.ValueOf(abi.ParseTopicsIntoMap),
		"ReadFixedBytes":      reflect.ValueOf(abi.ReadFixedBytes),
		"ReadInteger":         reflect.ValueOf(abi.ReadInteger),
		"Receive":             reflect.ValueOf(abi.Receive),
		"ResolveNameConflict": reflect.ValueOf(abi.ResolveNameConflict),
		"SliceTy":             reflect.ValueOf(abi.SliceTy),
		"StringTy":            reflect.ValueOf(abi.StringTy),
		"ToCamelCase":         reflect.ValueOf(abi.ToCamelCase),
		"TupleTy":             reflect.ValueOf(abi.TupleTy),
		"UintTy":              reflect.ValueOf(abi.UintTy),
		"UnpackRevert":        reflect.ValueOf(abi.UnpackRevert),

		// type definitions
		"ABI":                reflect.ValueOf((*abi.ABI)(nil)),
		"Argument":           reflect.ValueOf((*abi.Argument)(nil)),
		"ArgumentMarshaling": reflect.ValueOf((*abi.ArgumentMarshaling)(nil)),
		"Arguments":          reflect.ValueOf((*abi.Arguments)(nil)),
		"Error":              reflect.ValueOf((*abi.Error)(nil)),
		"Event":              reflect.ValueOf((*abi.Event)(nil)),
		"FunctionType":       reflect.ValueOf((*abi.FunctionType)(nil)),
		"Method":             reflect.ValueOf((*abi.Method)(nil)),
		"SelectorMarshaling": reflect.ValueOf((*abi.SelectorMarshaling)(nil)),
		"Type":               reflect.ValueOf((*abi.Type)(nil)),
	}
}
