// Code generated by 'yaegi extract github.com/ethereum/go-ethereum/core/types'. DO NOT EDIT.

package loader

import (
	"bytes"
	"github.com/ethereum/go-ethereum/common"
	"github.com/ethereum/go-ethereum/core/types"
	"go/constant"
	"go/token"
	"math/big"
	"reflect"
)

func init() {
	Symbols["github.com/ethereum/go-ethereum/core/types/types"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AccessListTxType":        reflect.ValueOf(constant.MakeFromLiteral("1", token.INT, 0)),
		"AddressToDelegation":     reflect.ValueOf(types.AddressToDelegation),
		"BlobSidecarVersion0":     reflect.ValueOf(types.BlobSidecarVersion0),
		"BlobSidecarVersion1":     reflect.ValueOf(types.BlobSidecarVersion1),
		"BlobTxType":              reflect.ValueOf(constant.MakeFromLiteral("3", token.INT, 0)),
		"Bloom9":                  reflect.ValueOf(types.Bloom9),
		"BloomBitLength":          reflect.ValueOf(constant.MakeFromLiteral("2048", token.INT, 0)),
		"BloomByteLength":         reflect.ValueOf(constant.MakeFromLiteral("256", token.INT, 0)),
		"BloomLookup":             reflect.ValueOf(types.BloomLookup),
		"BytesToBloom":            reflect.ValueOf(types.BytesToBloom),
		"CalcRequestsHash":        reflect.ValueOf(types.CalcRequestsHash),
		"CalcUncleHash":           reflect.ValueOf(types.CalcUncleHash),
		"CopyHeader":              reflect.ValueOf(types.CopyHeader),
		"CreateBloom":             reflect.ValueOf(types.CreateBloom),
		"DelegationPrefix":        reflect.ValueOf(&types.DelegationPrefix).Elem(),
		"DepositLogToRequest":     reflect.ValueOf(types.DepositLogToRequest),
		"DeriveSha":               reflect.ValueOf(types.DeriveSha),
		"DynamicFeeTxType":        reflect.ValueOf(constant.MakeFromLiteral("2", token.INT, 0)),
		"EmptyBinaryHash":         reflect.ValueOf(&types.EmptyBinaryHash).Elem(),
		"EmptyCodeHash":           reflect.ValueOf(&types.EmptyCodeHash).Elem(),
		"EmptyReceiptsHash":       reflect.ValueOf(&types.EmptyReceiptsHash).Elem(),
		"EmptyRequestsHash":       reflect.ValueOf(&types.EmptyRequestsHash).Elem(),
		"EmptyRootHash":           reflect.ValueOf(&types.EmptyRootHash).Elem(),
		"EmptyTxsHash":            reflect.ValueOf(&types.EmptyTxsHash).Elem(),
		"EmptyUncleHash":          reflect.ValueOf(&types.EmptyUncleHash).Elem(),
		"EmptyVerkleHash":         reflect.ValueOf(&types.EmptyVerkleHash).Elem(),
		"EmptyWithdrawalsHash":    reflect.ValueOf(&types.EmptyWithdrawalsHash).Elem(),
		"EncodeBlockReceiptLists": reflect.ValueOf(types.EncodeBlockReceiptLists),
		"EncodeNonce":             reflect.ValueOf(types.EncodeNonce),
		"ErrGasFeeCapTooLow":      reflect.ValueOf(&types.ErrGasFeeCapTooLow).Elem(),
		"ErrInvalidChainId":       reflect.ValueOf(&types.ErrInvalidChainId).Elem(),
		"ErrInvalidSig":           reflect.ValueOf(&types.ErrInvalidSig).Elem(),
		"ErrTxTypeNotSupported":   reflect.ValueOf(&types.ErrTxTypeNotSupported).Elem(),
		"ErrUint256Overflow":      reflect.ValueOf(&types.ErrUint256Overflow).Elem(),
		"ErrUnexpectedProtection": reflect.ValueOf(&types.ErrUnexpectedProtection).Elem(),
		"FullAccount":             reflect.ValueOf(types.FullAccount),
		"FullAccountRLP":          reflect.ValueOf(types.FullAccountRLP),
		"HashDifference":          reflect.ValueOf(types.HashDifference),
		"HeaderParentHashFromRLP": reflect.ValueOf(types.HeaderParentHashFromRLP),
		"LatestSigner":            reflect.ValueOf(types.LatestSigner),
		"LatestSignerForChainID":  reflect.ValueOf(types.LatestSignerForChainID),
		"LegacyTxType":            reflect.ValueOf(constant.MakeFromLiteral("0", token.INT, 0)),
		"MakeSigner":              reflect.ValueOf(types.MakeSigner),
		"MergeBloom":              reflect.ValueOf(types.MergeBloom),
		"MustSignNewTx":           reflect.ValueOf(types.MustSignNewTx),
		"NewBlobTxSidecar":        reflect.ValueOf(types.NewBlobTxSidecar),
		"NewBlock":                reflect.ValueOf(types.NewBlock),
		"NewBlockWithHeader":      reflect.ValueOf(types.NewBlockWithHeader),
		"NewCancunSigner":         reflect.ValueOf(types.NewCancunSigner),
		"NewContractCreation":     reflect.ValueOf(types.NewContractCreation),
		"NewEIP155Signer":         reflect.ValueOf(types.NewEIP155Signer),
		"NewEIP2930Signer":        reflect.ValueOf(types.NewEIP2930Signer),
		"NewEmptyStateAccount":    reflect.ValueOf(types.NewEmptyStateAccount),
		"NewLondonSigner":         reflect.ValueOf(types.NewLondonSigner),
		"NewPragueSigner":         reflect.ValueOf(types.NewPragueSigner),
		"NewReceipt":              reflect.ValueOf(types.NewReceipt),
		"NewTransaction":          reflect.ValueOf(types.NewTransaction),
		"NewTx":                   reflect.ValueOf(types.NewTx),
		"ParseDelegation":         reflect.ValueOf(types.ParseDelegation),
		"ReceiptStatusFailed":     reflect.ValueOf(types.ReceiptStatusFailed),
		"ReceiptStatusSuccessful": reflect.ValueOf(types.ReceiptStatusSuccessful),
		"Sender":                  reflect.ValueOf(types.Sender),
		"SetCodeTxType":           reflect.ValueOf(constant.MakeFromLiteral("4", token.INT, 0)),
		"SignNewTx":               reflect.ValueOf(types.SignNewTx),
		"SignSetCode":             reflect.ValueOf(types.SignSetCode),
		"SignTx":                  reflect.ValueOf(types.SignTx),
		"SlimAccountRLP":          reflect.ValueOf(types.SlimAccountRLP),
		"TxDifference":            reflect.ValueOf(types.TxDifference),

		// type definitions
		"AccessList":           reflect.ValueOf((*types.AccessList)(nil)),
		"AccessListTx":         reflect.ValueOf((*types.AccessListTx)(nil)),
		"AccessTuple":          reflect.ValueOf((*types.AccessTuple)(nil)),
		"Account":              reflect.ValueOf((*types.Account)(nil)),
		"BlobTx":               reflect.ValueOf((*types.BlobTx)(nil)),
		"BlobTxSidecar":        reflect.ValueOf((*types.BlobTxSidecar)(nil)),
		"Block":                reflect.ValueOf((*types.Block)(nil)),
		"BlockNonce":           reflect.ValueOf((*types.BlockNonce)(nil)),
		"Blocks":               reflect.ValueOf((*types.Blocks)(nil)),
		"Bloom":                reflect.ValueOf((*types.Bloom)(nil)),
		"Body":                 reflect.ValueOf((*types.Body)(nil)),
		"DerivableList":        reflect.ValueOf((*types.DerivableList)(nil)),
		"DeriveReceiptContext": reflect.ValueOf((*types.DeriveReceiptContext)(nil)),
		"DynamicFeeTx":         reflect.ValueOf((*types.DynamicFeeTx)(nil)),
		"EIP155Signer":         reflect.ValueOf((*types.EIP155Signer)(nil)),
		"ExecutionWitness":     reflect.ValueOf((*types.ExecutionWitness)(nil)),
		"FrontierSigner":       reflect.ValueOf((*types.FrontierSigner)(nil)),
		"GenesisAlloc":         reflect.ValueOf((*types.GenesisAlloc)(nil)),
		"Header":               reflect.ValueOf((*types.Header)(nil)),
		"HomesteadSigner":      reflect.ValueOf((*types.HomesteadSigner)(nil)),
		"LegacyTx":             reflect.ValueOf((*types.LegacyTx)(nil)),
		"ListHasher":           reflect.ValueOf((*types.ListHasher)(nil)),
		"Log":                  reflect.ValueOf((*types.Log)(nil)),
		"Receipt":              reflect.ValueOf((*types.Receipt)(nil)),
		"ReceiptForStorage":    reflect.ValueOf((*types.ReceiptForStorage)(nil)),
		"Receipts":             reflect.ValueOf((*types.Receipts)(nil)),
		"SetCodeAuthorization": reflect.ValueOf((*types.SetCodeAuthorization)(nil)),
		"SetCodeTx":            reflect.ValueOf((*types.SetCodeTx)(nil)),
		"Signer":               reflect.ValueOf((*types.Signer)(nil)),
		"SlimAccount":          reflect.ValueOf((*types.SlimAccount)(nil)),
		"StateAccount":         reflect.ValueOf((*types.StateAccount)(nil)),
		"Transaction":          reflect.ValueOf((*types.Transaction)(nil)),
		"Transactions":         reflect.ValueOf((*types.Transactions)(nil)),
		"TxByNonce":            reflect.ValueOf((*types.TxByNonce)(nil)),
		"TxData":               reflect.ValueOf((*types.TxData)(nil)),
		"Withdrawal":           reflect.ValueOf((*types.Withdrawal)(nil)),
		"Withdrawals":          reflect.ValueOf((*types.Withdrawals)(nil)),

		// interface wrapper definitions
		"_DerivableList": reflect.ValueOf((*_github_com_ethereum_go_ethereum_core_types_DerivableList)(nil)),
		"_ListHasher":    reflect.ValueOf((*_github_com_ethereum_go_ethereum_core_types_ListHasher)(nil)),
		"_Signer":        reflect.ValueOf((*_github_com_ethereum_go_ethereum_core_types_Signer)(nil)),
		"_TxData":        reflect.ValueOf((*_github_com_ethereum_go_ethereum_core_types_TxData)(nil)),
	}
}

// _github_com_ethereum_go_ethereum_core_types_DerivableList is an interface wrapper for DerivableList type
type _github_com_ethereum_go_ethereum_core_types_DerivableList struct {
	IValue       interface{}
	WEncodeIndex func(a0 int, a1 *bytes.Buffer)
	WLen         func() int
}

func (W _github_com_ethereum_go_ethereum_core_types_DerivableList) EncodeIndex(a0 int, a1 *bytes.Buffer) {
	W.WEncodeIndex(a0, a1)
}
func (W _github_com_ethereum_go_ethereum_core_types_DerivableList) Len() int {
	return W.WLen()
}

// _github_com_ethereum_go_ethereum_core_types_ListHasher is an interface wrapper for ListHasher type
type _github_com_ethereum_go_ethereum_core_types_ListHasher struct {
	IValue  interface{}
	WHash   func() common.Hash
	WReset  func()
	WUpdate func(key []byte, value []byte) error
}

func (W _github_com_ethereum_go_ethereum_core_types_ListHasher) Hash() common.Hash {
	return W.WHash()
}
func (W _github_com_ethereum_go_ethereum_core_types_ListHasher) Reset() {
	W.WReset()
}
func (W _github_com_ethereum_go_ethereum_core_types_ListHasher) Update(key []byte, value []byte) error {
	return W.WUpdate(key, value)
}

// _github_com_ethereum_go_ethereum_core_types_Signer is an interface wrapper for Signer type
type _github_com_ethereum_go_ethereum_core_types_Signer struct {
	IValue           interface{}
	WChainID         func() *big.Int
	WEqual           func(a0 types.Signer) bool
	WHash            func(tx *types.Transaction) common.Hash
	WSender          func(tx *types.Transaction) (common.Address, error)
	WSignatureValues func(tx *types.Transaction, sig []byte) (r *big.Int, s *big.Int, v *big.Int, err error)
}

func (W _github_com_ethereum_go_ethereum_core_types_Signer) ChainID() *big.Int {
	return W.WChainID()
}
func (W _github_com_ethereum_go_ethereum_core_types_Signer) Equal(a0 types.Signer) bool {
	return W.WEqual(a0)
}
func (W _github_com_ethereum_go_ethereum_core_types_Signer) Hash(tx *types.Transaction) common.Hash {
	return W.WHash(tx)
}
func (W _github_com_ethereum_go_ethereum_core_types_Signer) Sender(tx *types.Transaction) (common.Address, error) {
	return W.WSender(tx)
}
func (W _github_com_ethereum_go_ethereum_core_types_Signer) SignatureValues(tx *types.Transaction, sig []byte) (r *big.Int, s *big.Int, v *big.Int, err error) {
	return W.WSignatureValues(tx, sig)
}

// _github_com_ethereum_go_ethereum_core_types_TxData is an interface wrapper for TxData type
type _github_com_ethereum_go_ethereum_core_types_TxData struct {
	IValue interface{}
}
