// Code generated by 'yaegi extract github.com/holiman/uint256'. DO NOT EDIT.

package loader

import (
	"github.com/holiman/uint256"
	"reflect"
)

func init() {
	Symbols["github.com/holiman/uint256/uint256"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"ErrBadBufferLength":  reflect.ValueOf(&uint256.ErrBadBufferLength).Elem(),
		"ErrBadEncodedLength": reflect.ValueOf(&uint256.ErrBadEncodedLength).Elem(),
		"ErrBig256Range":      reflect.ValueOf(&uint256.ErrBig256Range).Elem(),
		"ErrEmptyNumber":      reflect.ValueOf(&uint256.ErrEmptyNumber).Elem(),
		"ErrEmptyString":      reflect.ValueOf(&uint256.ErrEmptyString).Elem(),
		"ErrLeadingZero":      reflect.ValueOf(&uint256.ErrLeadingZero).Elem(),
		"ErrMissingPrefix":    reflect.ValueOf(&uint256.ErrMissingPrefix).Elem(),
		"ErrSyntax":           reflect.ValueOf(&uint256.ErrSyntax).Elem(),
		"FromBig":             reflect.ValueOf(uint256.FromBig),
		"FromDecimal":         reflect.ValueOf(uint256.FromDecimal),
		"FromHex":             reflect.ValueOf(uint256.FromHex),
		"MustFromBig":         reflect.ValueOf(uint256.MustFromBig),
		"MustFromDecimal":     reflect.ValueOf(uint256.MustFromDecimal),
		"MustFromHex":         reflect.ValueOf(uint256.MustFromHex),
		"NewInt":              reflect.ValueOf(uint256.NewInt),
		"Reciprocal":          reflect.ValueOf(uint256.Reciprocal),

		// type definitions
		"Int": reflect.ValueOf((*uint256.Int)(nil)),
	}
}
