// Code generated by 'yaegi extract github.com/ethereum/go-ethereum/common'. DO NOT EDIT.

package loader

import (
	"github.com/ethereum/go-ethereum/common"
	"go/constant"
	"go/token"
	"reflect"
)

func init() {
	Symbols["github.com/ethereum/go-ethereum/common/common"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"AbsolutePath":                  reflect.ValueOf(common.AbsolutePath),
		"AddressLength":                 reflect.ValueOf(constant.MakeFromLiteral("20", token.INT, 0)),
		"Big0":                          reflect.ValueOf(&common.Big0).Elem(),
		"Big1":                          reflect.ValueOf(&common.Big1).Elem(),
		"Big2":                          reflect.ValueOf(&common.Big2).Elem(),
		"Big256":                        reflect.ValueOf(&common.Big256).Elem(),
		"Big257":                        reflect.ValueOf(&common.Big257).Elem(),
		"Big3":                          reflect.ValueOf(&common.Big3).Elem(),
		"Big32":                         reflect.ValueOf(&common.Big32).Elem(),
		"BigToAddress":                  reflect.ValueOf(common.BigToAddress),
		"BigToHash":                     reflect.ValueOf(common.BigToHash),
		"Bytes2Hex":                     reflect.ValueOf(common.Bytes2Hex),
		"BytesToAddress":                reflect.ValueOf(common.BytesToAddress),
		"BytesToHash":                   reflect.ValueOf(common.BytesToHash),
		"CalculateETA":                  reflect.ValueOf(common.CalculateETA),
		"CopyBytes":                     reflect.ValueOf(common.CopyBytes),
		"FileExist":                     reflect.ValueOf(common.FileExist),
		"FromHex":                       reflect.ValueOf(common.FromHex),
		"HashLength":                    reflect.ValueOf(constant.MakeFromLiteral("32", token.INT, 0)),
		"Hex2Bytes":                     reflect.ValueOf(common.Hex2Bytes),
		"Hex2BytesFixed":                reflect.ValueOf(common.Hex2BytesFixed),
		"HexToAddress":                  reflect.ValueOf(common.HexToAddress),
		"HexToHash":                     reflect.ValueOf(common.HexToHash),
		"IsHexAddress":                  reflect.ValueOf(common.IsHexAddress),
		"IsNonEmptyDir":                 reflect.ValueOf(common.IsNonEmptyDir),
		"LeftPadBytes":                  reflect.ValueOf(common.LeftPadBytes),
		"LoadJSON":                      reflect.ValueOf(common.LoadJSON),
		"MaxAddress":                    reflect.ValueOf(&common.MaxAddress).Elem(),
		"MaxHash":                       reflect.ValueOf(&common.MaxHash).Elem(),
		"NewMixedcaseAddress":           reflect.ValueOf(common.NewMixedcaseAddress),
		"NewMixedcaseAddressFromString": reflect.ValueOf(common.NewMixedcaseAddressFromString),
		"ParseHexOrString":              reflect.ValueOf(common.ParseHexOrString),
		"PrintDeprecationWarning":       reflect.ValueOf(common.PrintDeprecationWarning),
		"Report":                        reflect.ValueOf(common.Report),
		"RightPadBytes":                 reflect.ValueOf(common.RightPadBytes),
		"TrimLeftZeroes":                reflect.ValueOf(common.TrimLeftZeroes),
		"TrimRightZeroes":               reflect.ValueOf(common.TrimRightZeroes),
		"U2560":                         reflect.ValueOf(&common.U2560).Elem(),

		// type definitions
		"Address":           reflect.ValueOf((*common.Address)(nil)),
		"AddressEIP55":      reflect.ValueOf((*common.AddressEIP55)(nil)),
		"Decimal":           reflect.ValueOf((*common.Decimal)(nil)),
		"Hash":              reflect.ValueOf((*common.Hash)(nil)),
		"MixedcaseAddress":  reflect.ValueOf((*common.MixedcaseAddress)(nil)),
		"PrettyAge":         reflect.ValueOf((*common.PrettyAge)(nil)),
		"PrettyBytes":       reflect.ValueOf((*common.PrettyBytes)(nil)),
		"PrettyDuration":    reflect.ValueOf((*common.PrettyDuration)(nil)),
		"StorageSize":       reflect.ValueOf((*common.StorageSize)(nil)),
		"UnprefixedAddress": reflect.ValueOf((*common.UnprefixedAddress)(nil)),
		"UnprefixedHash":    reflect.ValueOf((*common.UnprefixedHash)(nil)),
	}
}
