// Code generated by 'yaegi extract github.com/ethpandaops/spamoor/scenarios/statebloat/erc20_bloater/contract'. DO NOT EDIT.

package loader

import (
	"github.com/ethpandaops/spamoor/scenarios/statebloat/erc20_bloater/contract"
	"reflect"
)

func init() {
	Symbols["github.com/ethpandaops/spamoor/scenarios/statebloat/erc20_bloater/contract/contract"] = map[string]reflect.Value{
		// function, constant and variable definitions
		"DeployERC20Bloater":        reflect.ValueOf(contract.DeployERC20Bloater),
		"ERC20BloaterABI":           reflect.ValueOf(&contract.ERC20BloaterABI).Elem(),
		"ERC20BloaterBin":           reflect.ValueOf(&contract.ERC20BloaterBin).Elem(),
		"ERC20BloaterMetaData":      reflect.ValueOf(&contract.ERC20BloaterMetaData).Elem(),
		"NewERC20Bloater":           reflect.ValueOf(contract.NewERC20Bloater),
		"NewERC20BloaterCaller":     reflect.ValueOf(contract.NewERC20BloaterCaller),
		"NewERC20BloaterFilterer":   reflect.ValueOf(contract.NewERC20BloaterFilterer),
		"NewERC20BloaterTransactor": reflect.ValueOf(contract.NewERC20BloaterTransactor),

		// type definitions
		"ERC20Bloater":                       reflect.ValueOf((*contract.ERC20Bloater)(nil)),
		"ERC20BloaterCaller":                 reflect.ValueOf((*contract.ERC20BloaterCaller)(nil)),
		"ERC20BloaterCallerRaw":              reflect.ValueOf((*contract.ERC20BloaterCallerRaw)(nil)),
		"ERC20BloaterCallerSession":          reflect.ValueOf((*contract.ERC20BloaterCallerSession)(nil)),
		"ERC20BloaterFilterer":               reflect.ValueOf((*contract.ERC20BloaterFilterer)(nil)),
		"ERC20BloaterRaw":                    reflect.ValueOf((*contract.ERC20BloaterRaw)(nil)),
		"ERC20BloaterSession":                reflect.ValueOf((*contract.ERC20BloaterSession)(nil)),
		"ERC20BloaterStorageBloated":         reflect.ValueOf((*contract.ERC20BloaterStorageBloated)(nil)),
		"ERC20BloaterStorageBloatedIterator": reflect.ValueOf((*contract.ERC20BloaterStorageBloatedIterator)(nil)),
		"ERC20BloaterTransactor":             reflect.ValueOf((*contract.ERC20BloaterTransactor)(nil)),
		"ERC20BloaterTransactorRaw":          reflect.ValueOf((*contract.ERC20BloaterTransactorRaw)(nil)),
		"ERC20BloaterTransactorSession":      reflect.ValueOf((*contract.ERC20BloaterTransactorSession)(nil)),
	}
}
